/*
 jQuery JavaScript Library v1.9.1
 http://jquery.com/

 Includes Sizzle.js
 http://sizzlejs.com/

 Copyright 2005, 2012 jQuery Foundation, Inc. and other contributors
 Released under the MIT license
 http://jquery.org/license

 Date: 2013-2-4
 Sizzle CSS Selector Engine
 Copyright 2012 jQuery Foundation and other contributors
 Released under the MIT license
 http://sizzlejs.com/
*/
var $jscomp={scope:{},findInternal:function(n,p,A){n instanceof String&&(n=String(n));for(var F=n.length,G=0;G<F;G++){var la=n[G];if(p.call(A,la,G,n))return{i:G,v:la}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(n,p,A){if(A.get||A.set)throw new TypeError("ES3 does not support getters and setters.");n!=Array.prototype&&n!=Object.prototype&&(n[p]=A.value)};
$jscomp.getGlobal=function(n){return"undefined"!=typeof window&&window===n?n:"undefined"!=typeof global&&null!=global?global:n};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(n,p,A,F){if(p){A=$jscomp.global;n=n.split(".");for(F=0;F<n.length-1;F++){var G=n[F];G in A||(A[G]={});A=A[G]}n=n[n.length-1];F=A[n];p=p(F);p!=F&&null!=p&&$jscomp.defineProperty(A,n,{configurable:!0,writable:!0,value:p})}};
$jscomp.polyfill("Array.prototype.find",function(n){return n?n:function(p,n){return $jscomp.findInternal(this,p,n).v}},"es6-impl","es3");
(function(n,p){function A(a){var b=a.length,d=c.type(a);return c.isWindow(a)?!1:1===a.nodeType&&b?!0:"array"===d||"function"!==d&&(0===b||"number"===typeof b&&0<b&&b-1 in a)}function F(a){var b=$a[a]={};c.each(a.match(S)||[],function(a,c){b[c]=!0});return b}function G(a,b,d,e){if(c.acceptData(a)){var f=c.expando,g="string"===typeof b,h=a.nodeType,k=h?c.cache:a,l=h?a[f]:a[f]&&f;if(l&&k[l]&&(e||k[l].data)||!g||d!==p){l||(h?a[f]=l=ba.pop()||c.guid++:l=f);k[l]||(k[l]={},h||(k[l].toJSON=c.noop));if("object"===
typeof b||"function"===typeof b)e?k[l]=c.extend(k[l],b):k[l].data=c.extend(k[l].data,b);a=k[l];e||(a.data||(a.data={}),a=a.data);d!==p&&(a[c.camelCase(b)]=d);g?(d=a[b],null==d&&(d=a[c.camelCase(b)])):d=a;return d}}}function la(a,b,d){if(c.acceptData(a)){var e,f,g,h=a.nodeType,k=h?c.cache:a,l=h?a[c.expando]:c.expando;if(k[l]){if(b&&(g=d?k[l]:k[l].data)){c.isArray(b)?b=b.concat(c.map(b,c.camelCase)):b in g?b=[b]:(b=c.camelCase(b),b=b in g?[b]:b.split(" "));e=0;for(f=b.length;e<f;e++)delete g[b[e]];
if(!(d?Fa:c.isEmptyObject)(g))return}if(!d&&(delete k[l].data,!Fa(k[l])))return;h?c.cleanData([a],!0):c.support.deleteExpando||k!=k.window?delete k[l]:k[l]=null}}}function ab(a,b,d){if(d===p&&1===a.nodeType)if(d="data-"+b.replace(Vb,"-$1").toLowerCase(),d=a.getAttribute(d),"string"===typeof d){try{d="true"===d?!0:"false"===d?!1:"null"===d?null:+d+""===d?+d:Wb.test(d)?c.parseJSON(d):d}catch(e){}c.data(a,b,d)}else d=p;return d}function Fa(a){for(var b in a)if(("data"!==b||!c.isEmptyObject(a[b]))&&"toJSON"!==
b)return!1;return!0}function pa(){return!0}function X(){return!1}function bb(a,b){do a=a[b];while(a&&1!==a.nodeType);return a}function cb(a,b,d){b=b||0;if(c.isFunction(b))return c.grep(a,function(a,c){return!!b.call(a,c,a)===d});if(b.nodeType)return c.grep(a,function(a){return a===b===d});if("string"===typeof b){var e=c.grep(a,function(a){return 1===a.nodeType});if(Xb.test(b))return c.filter(b,e,!d);b=c.filter(b,e)}return c.grep(a,function(a){return 0<=c.inArray(a,b)===d})}function db(a){var b=eb.split("|");
a=a.createDocumentFragment();if(a.createElement)for(;b.length;)a.createElement(b.pop());return a}function Yb(a,b){return a.getElementsByTagName(b)[0]||a.appendChild(a.ownerDocument.createElement(b))}function fb(a){var b=a.getAttributeNode("type");a.type=(b&&b.specified)+"/"+a.type;return a}function gb(a){var b=Zb.exec(a.type);b?a.type=b[1]:a.removeAttribute("type");return a}function Ga(a,b){for(var d,e=0;null!=(d=a[e]);e++)c._data(d,"globalEval",!b||c._data(b[e],"globalEval"))}function hb(a,b){if(1===
b.nodeType&&c.hasData(a)){var d,e,f;e=c._data(a);var g=c._data(b,e),h=e.events;if(h)for(d in delete g.handle,g.events={},h)for(e=0,f=h[d].length;e<f;e++)c.event.add(b,d,h[d][e]);g.data&&(g.data=c.extend({},g.data))}}function z(a,b){var d,e,f=0,g=typeof a.getElementsByTagName!==O?a.getElementsByTagName(b||"*"):typeof a.querySelectorAll!==O?a.querySelectorAll(b||"*"):p;if(!g)for(g=[],d=a.childNodes||a;null!=(e=d[f]);f++)!b||c.nodeName(e,b)?g.push(e):c.merge(g,z(e,b));return b===p||b&&c.nodeName(a,b)?
c.merge([a],g):g}function $b(a){Ha.test(a.type)&&(a.defaultChecked=a.checked)}function ib(a,b){if(b in a)return b;for(var c=b.charAt(0).toUpperCase()+b.slice(1),e=b,f=jb.length;f--;)if(b=jb[f]+c,b in a)return b;return e}function ma(a,b){a=b||a;return"none"===c.css(a,"display")||!c.contains(a.ownerDocument,a)}function kb(a,b){for(var d,e,f,g=[],h=0,k=a.length;h<k;h++)e=a[h],e.style&&(g[h]=c._data(e,"olddisplay"),d=e.style.display,b?(g[h]||"none"!==d||(e.style.display=""),""===e.style.display&&ma(e)&&
(g[h]=c._data(e,"olddisplay",lb(e.nodeName)))):g[h]||(f=ma(e),(d&&"none"!==d||!f)&&c._data(e,"olddisplay",f?d:c.css(e,"display"))));for(h=0;h<k;h++)e=a[h],!e.style||b&&"none"!==e.style.display&&""!==e.style.display||(e.style.display=b?g[h]||"":"none");return a}function mb(a,b,c){return(a=ac.exec(b))?Math.max(0,a[1]-(c||0))+(a[2]||"px"):b}function nb(a,b,d,e,f){b=d===(e?"border":"content")?4:"width"===b?1:0;for(var g=0;4>b;b+=2)"margin"===d&&(g+=c.css(a,d+Y[b],!0,f)),e?("content"===d&&(g-=c.css(a,
"padding"+Y[b],!0,f)),"margin"!==d&&(g-=c.css(a,"border"+Y[b]+"Width",!0,f))):(g+=c.css(a,"padding"+Y[b],!0,f),"padding"!==d&&(g+=c.css(a,"border"+Y[b]+"Width",!0,f)));return g}function ob(a,b,d){var e=!0,f="width"===b?a.offsetWidth:a.offsetHeight,g=B(a),h=c.support.boxSizing&&"border-box"===c.css(a,"boxSizing",!1,g);if(0>=f||null==f){f=ca(a,b,g);if(0>f||null==f)f=a.style[b];if(qa.test(f))return f;e=h&&(c.support.boxSizingReliable||f===a.style[b]);f=parseFloat(f)||0}return f+nb(a,b,d||(h?"border":
"content"),e,g)+"px"}function lb(a){var b=q,d=pb[a];d||(d=qb(a,b),"none"!==d&&d||(Z=(Z||c("<iframe frameborder='0' width='0' height='0'/>").css("cssText","display:block !important")).appendTo(b.documentElement),b=(Z[0].contentWindow||Z[0].contentDocument).document,b.write("<!doctype html><html><body>"),b.close(),d=qb(a,b),Z.detach()),pb[a]=d);return d}function qb(a,b){var d=c(b.createElement(a)).appendTo(b.body),e=c.css(d[0],"display");d.remove();return e}function Ia(a,b,d,e){var f;if(c.isArray(b))c.each(b,
function(b,c){d||bc.test(a)?e(a,c):Ia(a+"["+("object"===typeof c?b:"")+"]",c,d,e)});else if(d||"object"!==c.type(b))e(a,b);else for(f in b)Ia(a+"["+f+"]",b[f],d,e)}function rb(a){return function(b,d){"string"!==typeof b&&(d=b,b="*");var e,f=0,g=b.toLowerCase().match(S)||[];if(c.isFunction(d))for(;e=g[f++];)"+"===e[0]?(e=e.slice(1)||"*",(a[e]=a[e]||[]).unshift(d)):(a[e]=a[e]||[]).push(d)}}function sb(a,b,d,e){function f(k){var l;g[k]=!0;c.each(a[k]||[],function(a,c){var k=c(b,d,e);if("string"===typeof k&&
!h&&!g[k])return b.dataTypes.unshift(k),f(k),!1;if(h)return!(l=k)});return l}var g={},h=a===Ja;return f(b.dataTypes[0])||!g["*"]&&f("*")}function Ka(a,b){var d,e,f=c.ajaxSettings.flatOptions||{};for(e in b)b[e]!==p&&((f[e]?a:d||(d={}))[e]=b[e]);d&&c.extend(!0,a,d);return a}function tb(){try{return new n.XMLHttpRequest}catch(a){}}function ub(){setTimeout(function(){T=p});return T=c.now()}function cc(a,b){c.each(b,function(b,c){for(var d=(da[b]||[]).concat(da["*"]),e=0,h=d.length;e<h&&!d[e].call(a,
b,c);e++);})}function vb(a,b,d){var e,f=0,g=ra.length,h=c.Deferred().always(function(){delete k.elem}),k=function(){if(e)return!1;for(var b=T||ub(),b=Math.max(0,l.startTime+l.duration-b),c=1-(b/l.duration||0),d=0,f=l.tweens.length;d<f;d++)l.tweens[d].run(c);h.notifyWith(a,[l,c,b]);if(1>c&&f)return b;h.resolveWith(a,[l]);return!1},l=h.promise({elem:a,props:c.extend({},b),opts:c.extend(!0,{specialEasing:{}},d),originalProperties:b,originalOptions:d,startTime:T||ub(),duration:d.duration,tweens:[],createTween:function(b,
d){var e=c.Tween(a,l.opts,b,d,l.opts.specialEasing[b]||l.opts.easing);l.tweens.push(e);return e},stop:function(b){var c=0,d=b?l.tweens.length:0;if(e)return this;for(e=!0;c<d;c++)l.tweens[c].run(1);b?h.resolveWith(a,[l,b]):h.rejectWith(a,[l,b]);return this}});d=l.props;for(dc(d,l.opts.specialEasing);f<g;f++)if(b=ra[f].call(l,a,d,l.opts))return b;cc(l,d);c.isFunction(l.opts.start)&&l.opts.start.call(a,l);c.fx.timer(c.extend(k,{elem:a,anim:l,queue:l.opts.queue}));return l.progress(l.opts.progress).done(l.opts.done,
l.opts.complete).fail(l.opts.fail).always(l.opts.always)}function dc(a,b){var d,e,f,g,h;for(f in a)if(e=c.camelCase(f),g=b[e],d=a[f],c.isArray(d)&&(g=d[1],d=a[f]=d[0]),f!==e&&(a[e]=d,delete a[f]),(h=c.cssHooks[e])&&"expand"in h)for(f in d=h.expand(d),delete a[e],d)f in a||(a[f]=d[f],b[f]=g);else b[e]=g}function H(a,b,c,e,f){return new H.prototype.init(a,b,c,e,f)}function sa(a,b){var c,e={height:a},f=0;for(b=b?1:0;4>f;f+=2-b)c=Y[f],e["margin"+c]=e["padding"+c]=a;b&&(e.opacity=e.width=a);return e}function wb(a){return c.isWindow(a)?
a:9===a.nodeType?a.defaultView||a.parentWindow:!1}var za,xb,O=typeof p,q=n.document,ec=n.location,fc=n.jQuery,gc=n.$,Aa={},ba=[],yb=ba.concat,La=ba.push,P=ba.slice,zb=ba.indexOf,hc=Aa.toString,ea=Aa.hasOwnProperty,Ma="1.9.1".trim,c=function(a,b){return new c.fn.init(a,b,xb)},Ba=/[+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|)/.source,S=/\S+/g,ic=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,jc=/^(?:(<[\w\W]+>)[^>]*|#([\w-]*))$/,Ab=/^<(\w+)\s*\/?>(?:<\/\1>|)$/,kc=/^[\],:{}\s]*$/,lc=/(?:^|:|,)(?:\s*\[)+/g,mc=/\\(?:["\\\/bfnrt]|u[\da-fA-F]{4})/g,
nc=/"[^"\\\r\n]*"|true|false|null|-?(?:\d+\.|)\d+(?:[eE][+-]?\d+|)/g,oc=/^-ms-/,pc=/-([\da-z])/gi,qc=function(a,b){return b.toUpperCase()},U=function(a){if(q.addEventListener||"load"===a.type||"complete"===q.readyState)Bb(),c.ready()},Bb=function(){q.addEventListener?(q.removeEventListener("DOMContentLoaded",U,!1),n.removeEventListener("load",U,!1)):(q.detachEvent("onreadystatechange",U),n.detachEvent("onload",U))};c.fn=c.prototype={jquery:"1.9.1",constructor:c,init:function(a,b,d){var e;if(!a)return this;
if("string"===typeof a){e="<"===a.charAt(0)&&">"===a.charAt(a.length-1)&&3<=a.length?[null,a,null]:jc.exec(a);if(!e||!e[1]&&b)return!b||b.jquery?(b||d).find(a):this.constructor(b).find(a);if(e[1]){if(b=b instanceof c?b[0]:b,c.merge(this,c.parseHTML(e[1],b&&b.nodeType?b.ownerDocument||b:q,!0)),Ab.test(e[1])&&c.isPlainObject(b))for(e in b)if(c.isFunction(this[e]))this[e](b[e]);else this.attr(e,b[e])}else{if((b=q.getElementById(e[2]))&&b.parentNode){if(b.id!==e[2])return d.find(a);this.length=1;this[0]=
b}this.context=q;this.selector=a}return this}if(a.nodeType)return this.context=this[0]=a,this.length=1,this;if(c.isFunction(a))return d.ready(a);a.selector!==p&&(this.selector=a.selector,this.context=a.context);return c.makeArray(a,this)},selector:"",length:0,size:function(){return this.length},toArray:function(){return P.call(this)},get:function(a){return null==a?this.toArray():0>a?this[this.length+a]:this[a]},pushStack:function(a){a=c.merge(this.constructor(),a);a.prevObject=this;a.context=this.context;
return a},each:function(a,b){return c.each(this,a,b)},ready:function(a){c.ready.promise().done(a);return this},slice:function(){return this.pushStack(P.apply(this,arguments))},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},eq:function(a){var b=this.length;a=+a+(0>a?b:0);return this.pushStack(0<=a&&a<b?[this[a]]:[])},map:function(a){return this.pushStack(c.map(this,function(b,c){return a.call(b,c,b)}))},end:function(){return this.prevObject||this.constructor(null)},push:La,
sort:[].sort,splice:[].splice};c.fn.init.prototype=c.fn;c.extend=c.fn.extend=function(){var a,b,d,e,f,g=arguments[0]||{},h=1,k=arguments.length,l=!1;"boolean"===typeof g&&(l=g,g=arguments[1]||{},h=2);"object"===typeof g||c.isFunction(g)||(g={});k===h&&(g=this,--h);for(;h<k;h++)if(null!=(f=arguments[h]))for(e in f)a=g[e],d=f[e],g!==d&&(l&&d&&(c.isPlainObject(d)||(b=c.isArray(d)))?(b?(b=!1,a=a&&c.isArray(a)?a:[]):a=a&&c.isPlainObject(a)?a:{},g[e]=c.extend(l,a,d)):d!==p&&(g[e]=d));return g};c.extend({noConflict:function(a){n.$===
c&&(n.$=gc);a&&n.jQuery===c&&(n.jQuery=fc);return c},isReady:!1,readyWait:1,holdReady:function(a){a?c.readyWait++:c.ready(!0)},ready:function(a){if(!0===a?!--c.readyWait:!c.isReady){if(!q.body)return setTimeout(c.ready);c.isReady=!0;!0!==a&&0<--c.readyWait||(za.resolveWith(q,[c]),c.fn.trigger&&c(q).trigger("ready").off("ready"))}},isFunction:function(a){return"function"===c.type(a)},isArray:Array.isArray||function(a){return"array"===c.type(a)},isWindow:function(a){return null!=a&&a==a.window},isNumeric:function(a){return!isNaN(parseFloat(a))&&
isFinite(a)},type:function(a){return null==a?String(a):"object"===typeof a||"function"===typeof a?Aa[hc.call(a)]||"object":typeof a},isPlainObject:function(a){if(!a||"object"!==c.type(a)||a.nodeType||c.isWindow(a))return!1;try{if(a.constructor&&!ea.call(a,"constructor")&&!ea.call(a.constructor.prototype,"isPrototypeOf"))return!1}catch(d){return!1}for(var b in a);return b===p||ea.call(a,b)},isEmptyObject:function(a){for(var b in a)return!1;return!0},error:function(a){throw Error(a);},parseHTML:function(a,
b,d){if(!a||"string"!==typeof a)return null;"boolean"===typeof b&&(d=b,b=!1);b=b||q;var e=Ab.exec(a);d=!d&&[];if(e)return[b.createElement(e[1])];e=c.buildFragment([a],b,d);d&&c(d).remove();return c.merge([],e.childNodes)},parseJSON:function(a){if(n.JSON&&n.JSON.parse)return n.JSON.parse(a);if(null===a)return a;if("string"===typeof a&&(a=c.trim(a))&&kc.test(a.replace(mc,"@").replace(nc,"]").replace(lc,"")))return(new Function("return "+a))();c.error("Invalid JSON: "+a)},parseXML:function(a){var b,
d;if(!a||"string"!==typeof a)return null;try{n.DOMParser?(d=new DOMParser,b=d.parseFromString(a,"text/xml")):(b=new ActiveXObject("Microsoft.XMLDOM"),b.async="false",b.loadXML(a))}catch(e){b=p}b&&b.documentElement&&!b.getElementsByTagName("parsererror").length||c.error("Invalid XML: "+a);return b},noop:function(){},globalEval:function(a){a&&c.trim(a)&&(n.execScript||function(a){n.eval.call(n,a)})(a)},camelCase:function(a){return a.replace(oc,"ms-").replace(pc,qc)},nodeName:function(a,b){return a.nodeName&&
a.nodeName.toLowerCase()===b.toLowerCase()},each:function(a,b,c){var d,f=0,g=a.length;d=A(a);if(c)if(d)for(;f<g&&(d=b.apply(a[f],c),!1!==d);f++);else for(f in a){if(d=b.apply(a[f],c),!1===d)break}else if(d)for(;f<g&&(d=b.call(a[f],f,a[f]),!1!==d);f++);else for(f in a)if(d=b.call(a[f],f,a[f]),!1===d)break;return a},trim:Ma&&!Ma.call("\ufeff\u00a0")?function(a){return null==a?"":Ma.call(a)}:function(a){return null==a?"":(a+"").replace(ic,"")},makeArray:function(a,b){var d=b||[];null!=a&&(A(Object(a))?
c.merge(d,"string"===typeof a?[a]:a):La.call(d,a));return d},inArray:function(a,b,c){var d;if(b){if(zb)return zb.call(b,a,c);d=b.length;for(c=c?0>c?Math.max(0,d+c):c:0;c<d;c++)if(c in b&&b[c]===a)return c}return-1},merge:function(a,b){var c=b.length,e=a.length,f=0;if("number"===typeof c)for(;f<c;f++)a[e++]=b[f];else for(;b[f]!==p;)a[e++]=b[f++];a.length=e;return a},grep:function(a,b,c){var d,f=[],g=0,h=a.length;for(c=!!c;g<h;g++)d=!!b(a[g],g),c!==d&&f.push(a[g]);return f},map:function(a,b,c){var d,
f=0,g=a.length,h=[];if(A(a))for(;f<g;f++)d=b(a[f],f,c),null!=d&&(h[h.length]=d);else for(f in a)d=b(a[f],f,c),null!=d&&(h[h.length]=d);return yb.apply([],h)},guid:1,proxy:function(a,b){var d,e;"string"===typeof b&&(e=a[b],b=a,a=e);if(!c.isFunction(a))return p;d=P.call(arguments,2);e=function(){return a.apply(b||this,d.concat(P.call(arguments)))};e.guid=a.guid=a.guid||c.guid++;return e},access:function(a,b,d,e,f,g,h){var k=0,l=a.length,v=null==d;if("object"===c.type(d))for(k in f=!0,d)c.access(a,b,
k,d[k],!0,g,h);else if(e!==p&&(f=!0,c.isFunction(e)||(h=!0),v&&(h?(b.call(a,e),b=null):(v=b,b=function(a,b,d){return v.call(c(a),d)})),b))for(;k<l;k++)b(a[k],d,h?e:e.call(a[k],k,b(a[k],d)));return f?a:v?b.call(a):l?b(a[0],d):g},now:function(){return(new Date).getTime()}});c.ready.promise=function(a){if(!za)if(za=c.Deferred(),"complete"===q.readyState)setTimeout(c.ready);else if(q.addEventListener)q.addEventListener("DOMContentLoaded",U,!1),n.addEventListener("load",U,!1);else{q.attachEvent("onreadystatechange",
U);n.attachEvent("onload",U);var b=!1;try{b=null==n.frameElement&&q.documentElement}catch(d){}b&&b.doScroll&&function e(){if(!c.isReady){try{b.doScroll("left")}catch(f){return setTimeout(e,50)}Bb();c.ready()}}()}return za.promise(a)};c.each("Boolean Number String Function Array Date RegExp Object Error".split(" "),function(a,b){Aa["[object "+b+"]"]=b.toLowerCase()});xb=c(q);var $a={};c.Callbacks=function(a){a="string"===typeof a?$a[a]||F(a):c.extend({},a);var b,d,e,f,g,h,k=[],l=!a.once&&[],v=function(c){d=
a.memory&&c;e=!0;g=h||0;h=0;f=k.length;for(b=!0;k&&g<f;g++)if(!1===k[g].apply(c[0],c[1])&&a.stopOnFalse){d=!1;break}b=!1;k&&(l?l.length&&v(l.shift()):d?k=[]:M.disable())},M={add:function(){if(k){var e=k.length;(function Ca(b){c.each(b,function(b,d){var e=c.type(d);"function"===e?a.unique&&M.has(d)||k.push(d):d&&d.length&&"string"!==e&&Ca(d)})})(arguments);b?f=k.length:d&&(h=e,v(d))}return this},remove:function(){k&&c.each(arguments,function(a,d){for(var e;-1<(e=c.inArray(d,k,e));)k.splice(e,1),b&&
(e<=f&&f--,e<=g&&g--)});return this},has:function(a){return a?-1<c.inArray(a,k):!(!k||!k.length)},empty:function(){k=[];return this},disable:function(){k=l=d=p;return this},disabled:function(){return!k},lock:function(){l=p;d||M.disable();return this},locked:function(){return!l},fireWith:function(a,c){c=c||[];c=[a,c.slice?c.slice():c];!k||e&&!l||(b?l.push(c):v(c));return this},fire:function(){M.fireWith(this,arguments);return this},fired:function(){return!!e}};return M};c.extend({Deferred:function(a){var b=
[["resolve","done",c.Callbacks("once memory"),"resolved"],["reject","fail",c.Callbacks("once memory"),"rejected"],["notify","progress",c.Callbacks("memory")]],d="pending",e={state:function(){return d},always:function(){f.done(arguments).fail(arguments);return this},then:function(){var a=arguments;return c.Deferred(function(d){c.each(b,function(b,g){var h=g[0],k=c.isFunction(a[b])&&a[b];f[g[1]](function(){var a=k&&k.apply(this,arguments);if(a&&c.isFunction(a.promise))a.promise().done(d.resolve).fail(d.reject).progress(d.notify);
else d[h+"With"](this===e?d.promise():this,k?[a]:arguments)})});a=null}).promise()},promise:function(a){return null!=a?c.extend(a,e):e}},f={};e.pipe=e.then;c.each(b,function(a,c){var g=c[2],h=c[3];e[c[1]]=g.add;h&&g.add(function(){d=h},b[a^1][2].disable,b[2][2].lock);f[c[0]]=function(){f[c[0]+"With"](this===f?e:this,arguments);return this};f[c[0]+"With"]=g.fireWith});e.promise(f);a&&a.call(f,f);return f},when:function(a){var b=0,d=P.call(arguments),e=d.length,f=1!==e||a&&c.isFunction(a.promise)?e:
0,g=1===f?a:c.Deferred(),h=function(a,b,c){return function(d){b[a]=this;c[a]=1<arguments.length?P.call(arguments):d;c===k?g.notifyWith(b,c):--f||g.resolveWith(b,c)}},k,l,p;if(1<e)for(k=Array(e),l=Array(e),p=Array(e);b<e;b++)d[b]&&c.isFunction(d[b].promise)?d[b].promise().done(h(b,p,d)).fail(g.reject).progress(h(b,l,k)):--f;f||g.resolveWith(p,d);return g.promise()}});c.support=function(){var a,b,d,e,f,g,h,k=q.createElement("div");k.setAttribute("className","t");k.innerHTML="  <link/><table></table><a href='/a'>a</a><input type='checkbox'/>";
b=k.getElementsByTagName("*");d=k.getElementsByTagName("a")[0];if(!b||!d||!b.length)return{};e=q.createElement("select");f=e.appendChild(q.createElement("option"));b=k.getElementsByTagName("input")[0];d.style.cssText="top:1px;float:left;opacity:.5";a={getSetAttribute:"t"!==k.className,leadingWhitespace:3===k.firstChild.nodeType,tbody:!k.getElementsByTagName("tbody").length,htmlSerialize:!!k.getElementsByTagName("link").length,style:/top/.test(d.getAttribute("style")),hrefNormalized:"/a"===d.getAttribute("href"),
opacity:/^0.5/.test(d.style.opacity),cssFloat:!!d.style.cssFloat,checkOn:!!b.value,optSelected:f.selected,enctype:!!q.createElement("form").enctype,html5Clone:"<:nav></:nav>"!==q.createElement("nav").cloneNode(!0).outerHTML,boxModel:"CSS1Compat"===q.compatMode,deleteExpando:!0,noCloneEvent:!0,inlineBlockNeedsLayout:!1,shrinkWrapBlocks:!1,reliableMarginRight:!0,boxSizingReliable:!0,pixelPosition:!1};b.checked=!0;a.noCloneChecked=b.cloneNode(!0).checked;e.disabled=!0;a.optDisabled=!f.disabled;try{delete k.test}catch(l){a.deleteExpando=
!1}b=q.createElement("input");b.setAttribute("value","");a.input=""===b.getAttribute("value");b.value="t";b.setAttribute("type","radio");a.radioValue="t"===b.value;b.setAttribute("checked","t");b.setAttribute("name","t");d=q.createDocumentFragment();d.appendChild(b);a.appendChecked=b.checked;a.checkClone=d.cloneNode(!0).cloneNode(!0).lastChild.checked;k.attachEvent&&(k.attachEvent("onclick",function(){a.noCloneEvent=!1}),k.cloneNode(!0).click());for(h in{submit:!0,change:!0,focusin:!0})k.setAttribute(d=
"on"+h,"t"),a[h+"Bubbles"]=d in n||!1===k.attributes[d].expando;k.style.backgroundClip="content-box";k.cloneNode(!0).style.backgroundClip="";a.clearCloneStyle="content-box"===k.style.backgroundClip;c(function(){var b,c,d=q.getElementsByTagName("body")[0];d&&(b=q.createElement("div"),b.style.cssText="border:0;width:0;height:0;position:absolute;top:0;left:-9999px;margin-top:1px",d.appendChild(b).appendChild(k),k.innerHTML="<table><tr><td></td><td>t</td></tr></table>",c=k.getElementsByTagName("td"),
c[0].style.cssText="padding:0;margin:0;border:0;display:none",g=0===c[0].offsetHeight,c[0].style.display="",c[1].style.display="none",a.reliableHiddenOffsets=g&&0===c[0].offsetHeight,k.innerHTML="",k.style.cssText="box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;padding:1px;border:1px;display:block;width:4px;margin-top:1%;position:absolute;top:1%;",a.boxSizing=4===k.offsetWidth,a.doesNotIncludeMarginInBodyOffset=1!==d.offsetTop,n.getComputedStyle&&(a.pixelPosition="1%"!==
(n.getComputedStyle(k,null)||{}).top,a.boxSizingReliable="4px"===(n.getComputedStyle(k,null)||{width:"4px"}).width,c=k.appendChild(q.createElement("div")),c.style.cssText=k.style.cssText="padding:0;margin:0;border:0;display:block;box-sizing:content-box;-moz-box-sizing:content-box;-webkit-box-sizing:content-box;",c.style.marginRight=c.style.width="0",k.style.width="1px",a.reliableMarginRight=!parseFloat((n.getComputedStyle(c,null)||{}).marginRight)),typeof k.style.zoom!==O&&(k.innerHTML="",k.style.cssText=
"padding:0;margin:0;border:0;display:block;box-sizing:content-box;-moz-box-sizing:content-box;-webkit-box-sizing:content-box;width:1px;padding:1px;display:inline;zoom:1",a.inlineBlockNeedsLayout=3===k.offsetWidth,k.style.display="block",k.innerHTML="<div></div>",k.firstChild.style.width="5px",a.shrinkWrapBlocks=3!==k.offsetWidth,a.inlineBlockNeedsLayout&&(d.style.zoom=1)),d.removeChild(b),k=null)});b=e=d=f=d=b=null;return a}();var Wb=/(?:\{[\s\S]*\}|\[[\s\S]*\])$/,Vb=/([A-Z])/g;c.extend({cache:{},
expando:"jQuery"+("1.9.1"+Math.random()).replace(/\D/g,""),noData:{embed:!0,object:"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000",applet:!0},hasData:function(a){a=a.nodeType?c.cache[a[c.expando]]:a[c.expando];return!!a&&!Fa(a)},data:function(a,b,c){return G(a,b,c)},removeData:function(a,b){return la(a,b)},_data:function(a,b,c){return G(a,b,c,!0)},_removeData:function(a,b){return la(a,b,!0)},acceptData:function(a){if(a.nodeType&&1!==a.nodeType&&9!==a.nodeType)return!1;var b=a.nodeName&&c.noData[a.nodeName.toLowerCase()];
return!b||!0!==b&&a.getAttribute("classid")===b}});c.fn.extend({data:function(a,b){var d,e,f=this[0],g=0,h=null;if(a===p){if(this.length&&(h=c.data(f),1===f.nodeType&&!c._data(f,"parsedAttrs"))){for(d=f.attributes;g<d.length;g++)e=d[g].name,e.indexOf("data-")||(e=c.camelCase(e.slice(5)),ab(f,e,h[e]));c._data(f,"parsedAttrs",!0)}return h}return"object"===typeof a?this.each(function(){c.data(this,a)}):c.access(this,function(b){if(b===p)return f?ab(f,a,c.data(f,a)):null;this.each(function(){c.data(this,
a,b)})},null,b,1<arguments.length,null,!0)},removeData:function(a){return this.each(function(){c.removeData(this,a)})}});c.extend({queue:function(a,b,d){var e;if(a)return b=(b||"fx")+"queue",e=c._data(a,b),d&&(!e||c.isArray(d)?e=c._data(a,b,c.makeArray(d)):e.push(d)),e||[]},dequeue:function(a,b){b=b||"fx";var d=c.queue(a,b),e=d.length,f=d.shift(),g=c._queueHooks(a,b),h=function(){c.dequeue(a,b)};"inprogress"===f&&(f=d.shift(),e--);if(g.cur=f)"fx"===b&&d.unshift("inprogress"),delete g.stop,f.call(a,
h,g);!e&&g&&g.empty.fire()},_queueHooks:function(a,b){var d=b+"queueHooks";return c._data(a,d)||c._data(a,d,{empty:c.Callbacks("once memory").add(function(){c._removeData(a,b+"queue");c._removeData(a,d)})})}});c.fn.extend({queue:function(a,b){var d=2;"string"!==typeof a&&(b=a,a="fx",d--);return arguments.length<d?c.queue(this[0],a):b===p?this:this.each(function(){var d=c.queue(this,a,b);c._queueHooks(this,a);"fx"===a&&"inprogress"!==d[0]&&c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,
a)})},delay:function(a,b){a=c.fx?c.fx.speeds[a]||a:a;return this.queue(b||"fx",function(b,c){var d=setTimeout(b,a);c.stop=function(){clearTimeout(d)}})},clearQueue:function(a){return this.queue(a||"fx",[])},promise:function(a,b){var d,e=1,f=c.Deferred(),g=this,h=this.length,k=function(){--e||f.resolveWith(g,[g])};"string"!==typeof a&&(b=a,a=p);for(a=a||"fx";h--;)(d=c._data(g[h],a+"queueHooks"))&&d.empty&&(e++,d.empty.add(k));k();return f.promise(b)}});var ga,Cb,Oa=/[\t\r\n]/g,rc=/\r/g,sc=/^(?:input|select|textarea|button|object)$/i,
tc=/^(?:a|area)$/i,Db=/^(?:checked|selected|autofocus|autoplay|async|controls|defer|disabled|hidden|loop|multiple|open|readonly|required|scoped)$/i,Pa=/^(?:checked|selected)$/i,Q=c.support.getSetAttribute,Qa=c.support.input;c.fn.extend({attr:function(a,b){return c.access(this,c.attr,a,b,1<arguments.length)},removeAttr:function(a){return this.each(function(){c.removeAttr(this,a)})},prop:function(a,b){return c.access(this,c.prop,a,b,1<arguments.length)},removeProp:function(a){a=c.propFix[a]||a;return this.each(function(){try{this[a]=
p,delete this[a]}catch(b){}})},addClass:function(a){var b,d,e,f,g,h=0,k=this.length;b="string"===typeof a&&a;if(c.isFunction(a))return this.each(function(b){c(this).addClass(a.call(this,b,this.className))});if(b)for(b=(a||"").match(S)||[];h<k;h++)if(d=this[h],e=1===d.nodeType&&(d.className?(" "+d.className+" ").replace(Oa," "):" ")){for(g=0;f=b[g++];)0>e.indexOf(" "+f+" ")&&(e+=f+" ");d.className=c.trim(e)}return this},removeClass:function(a){var b,d,e,f,g,h=0,k=this.length;b=0===arguments.length||
"string"===typeof a&&a;if(c.isFunction(a))return this.each(function(b){c(this).removeClass(a.call(this,b,this.className))});if(b)for(b=(a||"").match(S)||[];h<k;h++)if(d=this[h],e=1===d.nodeType&&(d.className?(" "+d.className+" ").replace(Oa," "):"")){for(g=0;f=b[g++];)for(;0<=e.indexOf(" "+f+" ");)e=e.replace(" "+f+" "," ");d.className=a?c.trim(e):""}return this},toggleClass:function(a,b){var d=typeof a,e="boolean"===typeof b;return c.isFunction(a)?this.each(function(d){c(this).toggleClass(a.call(this,
d,this.className,b),b)}):this.each(function(){if("string"===d)for(var f,g=0,h=c(this),k=b,l=a.match(S)||[];f=l[g++];)k=e?k:!h.hasClass(f),h[k?"addClass":"removeClass"](f);else if(d===O||"boolean"===d)this.className&&c._data(this,"__className__",this.className),this.className=this.className||!1===a?"":c._data(this,"__className__")||""})},hasClass:function(a){a=" "+a+" ";for(var b=0,c=this.length;b<c;b++)if(1===this[b].nodeType&&0<=(" "+this[b].className+" ").replace(Oa," ").indexOf(a))return!0;return!1},
val:function(a){var b,d,e,f=this[0];if(arguments.length)return e=c.isFunction(a),this.each(function(b){var f=c(this);1===this.nodeType&&(b=e?a.call(this,b,f.val()):a,null==b?b="":"number"===typeof b?b+="":c.isArray(b)&&(b=c.map(b,function(a){return null==a?"":a+""})),d=c.valHooks[this.type]||c.valHooks[this.nodeName.toLowerCase()],d&&"set"in d&&d.set(this,b,"value")!==p||(this.value=b))});if(f){if((d=c.valHooks[f.type]||c.valHooks[f.nodeName.toLowerCase()])&&"get"in d&&(b=d.get(f,"value"))!==p)return b;
b=f.value;return"string"===typeof b?b.replace(rc,""):null==b?"":b}}});c.extend({valHooks:{option:{get:function(a){var b=a.attributes.value;return!b||b.specified?a.value:a.text}},select:{get:function(a){for(var b,d=a.options,e=a.selectedIndex,f=(a="select-one"===a.type||0>e)?null:[],g=a?e+1:d.length,h=0>e?g:a?e:0;h<g;h++)if(b=d[h],!(!b.selected&&h!==e||(c.support.optDisabled?b.disabled:null!==b.getAttribute("disabled"))||b.parentNode.disabled&&c.nodeName(b.parentNode,"optgroup"))){b=c(b).val();if(a)return b;
f.push(b)}return f},set:function(a,b){var d=c.makeArray(b);c(a).find("option").each(function(){this.selected=0<=c.inArray(c(this).val(),d)});d.length||(a.selectedIndex=-1);return d}}},attr:function(a,b,d){var e,f,g;f=a.nodeType;if(a&&3!==f&&8!==f&&2!==f){if(typeof a.getAttribute===O)return c.prop(a,b,d);if(f=1!==f||!c.isXMLDoc(a))b=b.toLowerCase(),e=c.attrHooks[b]||(Db.test(b)?Cb:ga);if(d!==p)if(null===d)c.removeAttr(a,b);else{if(e&&f&&"set"in e&&(g=e.set(a,d,b))!==p)return g;a.setAttribute(b,d+"");
return d}else{if(e&&f&&"get"in e&&null!==(g=e.get(a,b)))return g;typeof a.getAttribute!==O&&(g=a.getAttribute(b));return null==g?p:g}}},removeAttr:function(a,b){var d,e,f=0,g=b&&b.match(S);if(g&&1===a.nodeType)for(;d=g[f++];)e=c.propFix[d]||d,Db.test(d)?!Q&&Pa.test(d)?a[c.camelCase("default-"+d)]=a[e]=!1:a[e]=!1:c.attr(a,d,""),a.removeAttribute(Q?d:e)},attrHooks:{type:{set:function(a,b){if(!c.support.radioValue&&"radio"===b&&c.nodeName(a,"input")){var d=a.value;a.setAttribute("type",b);d&&(a.value=
d);return b}}}},propFix:{tabindex:"tabIndex",readonly:"readOnly","for":"htmlFor","class":"className",maxlength:"maxLength",cellspacing:"cellSpacing",cellpadding:"cellPadding",rowspan:"rowSpan",colspan:"colSpan",usemap:"useMap",frameborder:"frameBorder",contenteditable:"contentEditable"},prop:function(a,b,d){var e,f,g=a.nodeType;if(a&&3!==g&&8!==g&&2!==g)return 1===g&&c.isXMLDoc(a)||(b=c.propFix[b]||b,f=c.propHooks[b]),d!==p?f&&"set"in f&&(e=f.set(a,d,b))!==p?e:a[b]=d:f&&"get"in f&&null!==(e=f.get(a,
b))?e:a[b]},propHooks:{tabIndex:{get:function(a){var b=a.getAttributeNode("tabindex");return b&&b.specified?parseInt(b.value,10):sc.test(a.nodeName)||tc.test(a.nodeName)&&a.href?0:p}}}});Cb={get:function(a,b){var d=c.prop(a,b),e="boolean"===typeof d&&a.getAttribute(b);return(d="boolean"===typeof d?Qa&&Q?null!=e:Pa.test(b)?a[c.camelCase("default-"+b)]:!!e:a.getAttributeNode(b))&&!1!==d.value?b.toLowerCase():p},set:function(a,b,d){!1===b?c.removeAttr(a,d):Qa&&Q||!Pa.test(d)?a.setAttribute(!Q&&c.propFix[d]||
d,d):a[c.camelCase("default-"+d)]=a[d]=!0;return d}};Qa&&Q||(c.attrHooks.value={get:function(a,b){var d=a.getAttributeNode(b);return c.nodeName(a,"input")?a.defaultValue:d&&d.specified?d.value:p},set:function(a,b,d){if(c.nodeName(a,"input"))a.defaultValue=b;else return ga&&ga.set(a,b,d)}});Q||(ga=c.valHooks.button={get:function(a,b){var c=a.getAttributeNode(b);return c&&("id"===b||"name"===b||"coords"===b?""!==c.value:c.specified)?c.value:p},set:function(a,b,c){var d=a.getAttributeNode(c);d||a.setAttributeNode(d=
a.ownerDocument.createAttribute(c));d.value=b+="";return"value"===c||b===a.getAttribute(c)?b:p}},c.attrHooks.contenteditable={get:ga.get,set:function(a,b,c){ga.set(a,""===b?!1:b,c)}},c.each(["width","height"],function(a,b){c.attrHooks[b]=c.extend(c.attrHooks[b],{set:function(a,c){if(""===c)return a.setAttribute(b,"auto"),c}})}));c.support.hrefNormalized||(c.each(["href","src","width","height"],function(a,b){c.attrHooks[b]=c.extend(c.attrHooks[b],{get:function(a){a=a.getAttribute(b,2);return null==
a?p:a}})}),c.each(["href","src"],function(a,b){c.propHooks[b]={get:function(a){return a.getAttribute(b,4)}}}));c.support.style||(c.attrHooks.style={get:function(a){return a.style.cssText||p},set:function(a,b){return a.style.cssText=b+""}});c.support.optSelected||(c.propHooks.selected=c.extend(c.propHooks.selected,{get:function(a){if(a=a.parentNode)a.selectedIndex,a.parentNode&&a.parentNode.selectedIndex;return null}}));c.support.enctype||(c.propFix.enctype="encoding");c.support.checkOn||c.each(["radio",
"checkbox"],function(){c.valHooks[this]={get:function(a){return null===a.getAttribute("value")?"on":a.value}}});c.each(["radio","checkbox"],function(){c.valHooks[this]=c.extend(c.valHooks[this],{set:function(a,b){if(c.isArray(b))return a.checked=0<=c.inArray(c(a).val(),b)}})});var Ra=/^(?:input|select|textarea)$/i,uc=/^key/,vc=/^(?:mouse|contextmenu)|click/,Eb=/^(?:focusinfocus|focusoutblur)$/,Fb=/^([^.]*)(?:\.(.+)|)$/;c.event={global:{},add:function(a,b,d,e,f){var g,h,k,l,v,n,m,r,q;if(k=c._data(a)){d.handler&&
(l=d,d=l.handler,f=l.selector);d.guid||(d.guid=c.guid++);(h=k.events)||(h=k.events={});(v=k.handle)||(v=k.handle=function(a){return typeof c===O||a&&c.event.triggered===a.type?p:c.event.dispatch.apply(v.elem,arguments)},v.elem=a);b=(b||"").match(S)||[""];for(k=b.length;k--;)g=Fb.exec(b[k])||[],r=n=g[1],q=(g[2]||"").split(".").sort(),g=c.event.special[r]||{},r=(f?g.delegateType:g.bindType)||r,g=c.event.special[r]||{},n=c.extend({type:r,origType:n,data:e,handler:d,guid:d.guid,selector:f,needsContext:f&&
c.expr.match.needsContext.test(f),namespace:q.join(".")},l),(m=h[r])||(m=h[r]=[],m.delegateCount=0,g.setup&&!1!==g.setup.call(a,e,q,v)||(a.addEventListener?a.addEventListener(r,v,!1):a.attachEvent&&a.attachEvent("on"+r,v))),g.add&&(g.add.call(a,n),n.handler.guid||(n.handler.guid=d.guid)),f?m.splice(m.delegateCount++,0,n):m.push(n),c.event.global[r]=!0;a=null}},remove:function(a,b,d,e,f){var g,h,k,l,p,n,m,r,q,Na,A,z=c.hasData(a)&&c._data(a);if(z&&(n=z.events)){b=(b||"").match(S)||[""];for(p=b.length;p--;)if(k=
Fb.exec(b[p])||[],q=A=k[1],Na=(k[2]||"").split(".").sort(),q){m=c.event.special[q]||{};q=(e?m.delegateType:m.bindType)||q;r=n[q]||[];k=k[2]&&new RegExp("(^|\\.)"+Na.join("\\.(?:.*\\.|)")+"(\\.|$)");for(l=g=r.length;g--;)h=r[g],!f&&A!==h.origType||d&&d.guid!==h.guid||k&&!k.test(h.namespace)||e&&e!==h.selector&&("**"!==e||!h.selector)||(r.splice(g,1),h.selector&&r.delegateCount--,m.remove&&m.remove.call(a,h));l&&!r.length&&(m.teardown&&!1!==m.teardown.call(a,Na,z.handle)||c.removeEvent(a,q,z.handle),
delete n[q])}else for(q in n)c.event.remove(a,q+b[p],d,e,!0);c.isEmptyObject(n)&&(delete z.handle,c._removeData(a,"events"))}},trigger:function(a,b,d,e){var f,g,h,k,l,v,M=[d||q],m=ea.call(a,"type")?a.type:a;l=ea.call(a,"namespace")?a.namespace.split("."):[];h=f=d=d||q;if(3!==d.nodeType&&8!==d.nodeType&&!Eb.test(m+c.event.triggered)&&(0<=m.indexOf(".")&&(l=m.split("."),m=l.shift(),l.sort()),g=0>m.indexOf(":")&&"on"+m,a=a[c.expando]?a:new c.Event(m,"object"===typeof a&&a),a.isTrigger=!0,a.namespace=
l.join("."),a.namespace_re=a.namespace?new RegExp("(^|\\.)"+l.join("\\.(?:.*\\.|)")+"(\\.|$)"):null,a.result=p,a.target||(a.target=d),b=null==b?[a]:c.makeArray(b,[a]),l=c.event.special[m]||{},e||!l.trigger||!1!==l.trigger.apply(d,b))){if(!e&&!l.noBubble&&!c.isWindow(d)){k=l.delegateType||m;Eb.test(k+m)||(h=h.parentNode);for(;h;h=h.parentNode)M.push(h),f=h;f===(d.ownerDocument||q)&&M.push(f.defaultView||f.parentWindow||n)}for(v=0;(h=M[v++])&&!a.isPropagationStopped();)a.type=1<v?k:l.bindType||m,(f=
(c._data(h,"events")||{})[a.type]&&c._data(h,"handle"))&&f.apply(h,b),(f=g&&h[g])&&c.acceptData(h)&&f.apply&&!1===f.apply(h,b)&&a.preventDefault();a.type=m;if(!(e||a.isDefaultPrevented()||l._default&&!1!==l._default.apply(d.ownerDocument,b)||"click"===m&&c.nodeName(d,"a"))&&c.acceptData(d)&&g&&d[m]&&!c.isWindow(d)){(f=d[g])&&(d[g]=null);c.event.triggered=m;try{d[m]()}catch(r){}c.event.triggered=p;f&&(d[g]=f)}return a.result}},dispatch:function(a){a=c.event.fix(a);var b,d,e,f,g,h=P.call(arguments);
b=(c._data(this,"events")||{})[a.type]||[];var k=c.event.special[a.type]||{};h[0]=a;a.delegateTarget=this;if(!k.preDispatch||!1!==k.preDispatch.call(this,a)){g=c.event.handlers.call(this,a,b);for(b=0;(e=g[b++])&&!a.isPropagationStopped();)for(a.currentTarget=e.elem,f=0;(d=e.handlers[f++])&&!a.isImmediatePropagationStopped();)if(!a.namespace_re||a.namespace_re.test(d.namespace))a.handleObj=d,a.data=d.data,d=((c.event.special[d.origType]||{}).handle||d.handler).apply(e.elem,h),d!==p&&!1===(a.result=
d)&&(a.preventDefault(),a.stopPropagation());k.postDispatch&&k.postDispatch.call(this,a);return a.result}},handlers:function(a,b){var d,e,f,g,h=[],k=b.delegateCount,l=a.target;if(k&&l.nodeType&&(!a.button||"click"!==a.type))for(;l!=this;l=l.parentNode||this)if(1===l.nodeType&&(!0!==l.disabled||"click"!==a.type)){f=[];for(g=0;g<k;g++)e=b[g],d=e.selector+" ",f[d]===p&&(f[d]=e.needsContext?0<=c(d,this).index(l):c.find(d,this,null,[l]).length),f[d]&&f.push(e);f.length&&h.push({elem:l,handlers:f})}k<b.length&&
h.push({elem:this,handlers:b.slice(k)});return h},fix:function(a){if(a[c.expando])return a;var b,d,e;b=a.type;var f=a,g=this.fixHooks[b];g||(this.fixHooks[b]=g=vc.test(b)?this.mouseHooks:uc.test(b)?this.keyHooks:{});e=g.props?this.props.concat(g.props):this.props;a=new c.Event(f);for(b=e.length;b--;)d=e[b],a[d]=f[d];a.target||(a.target=f.srcElement||q);3===a.target.nodeType&&(a.target=a.target.parentNode);a.metaKey=!!a.metaKey;return g.filter?g.filter(a,f):a},props:"altKey bubbles cancelable ctrlKey currentTarget eventPhase metaKey relatedTarget shiftKey target timeStamp view which".split(" "),
fixHooks:{},keyHooks:{props:["char","charCode","key","keyCode"],filter:function(a,b){null==a.which&&(a.which=null!=b.charCode?b.charCode:b.keyCode);return a}},mouseHooks:{props:"button buttons clientX clientY fromElement offsetX offsetY pageX pageY screenX screenY toElement".split(" "),filter:function(a,b){var c,e,f=b.button,g=b.fromElement;null==a.pageX&&null!=b.clientX&&(c=a.target.ownerDocument||q,e=c.documentElement,c=c.body,a.pageX=b.clientX+(e&&e.scrollLeft||c&&c.scrollLeft||0)-(e&&e.clientLeft||
c&&c.clientLeft||0),a.pageY=b.clientY+(e&&e.scrollTop||c&&c.scrollTop||0)-(e&&e.clientTop||c&&c.clientTop||0));!a.relatedTarget&&g&&(a.relatedTarget=g===a.target?b.toElement:g);a.which||f===p||(a.which=f&1?1:f&2?3:f&4?2:0);return a}},special:{load:{noBubble:!0},click:{trigger:function(){if(c.nodeName(this,"input")&&"checkbox"===this.type&&this.click)return this.click(),!1}},focus:{trigger:function(){if(this!==q.activeElement&&this.focus)try{return this.focus(),!1}catch(a){}},delegateType:"focusin"},
blur:{trigger:function(){if(this===q.activeElement&&this.blur)return this.blur(),!1},delegateType:"focusout"},beforeunload:{postDispatch:function(a){a.result!==p&&(a.originalEvent.returnValue=a.result)}}},simulate:function(a,b,d,e){a=c.extend(new c.Event,d,{type:a,isSimulated:!0,originalEvent:{}});e?c.event.trigger(a,null,b):c.event.dispatch.call(b,a);a.isDefaultPrevented()&&d.preventDefault()}};c.removeEvent=q.removeEventListener?function(a,b,c){a.removeEventListener&&a.removeEventListener(b,c,!1)}:
function(a,b,c){b="on"+b;a.detachEvent&&(typeof a[b]===O&&(a[b]=null),a.detachEvent(b,c))};c.Event=function(a,b){if(!(this instanceof c.Event))return new c.Event(a,b);a&&a.type?(this.originalEvent=a,this.type=a.type,this.isDefaultPrevented=a.defaultPrevented||!1===a.returnValue||a.getPreventDefault&&a.getPreventDefault()?pa:X):this.type=a;b&&c.extend(this,b);this.timeStamp=a&&a.timeStamp||c.now();this[c.expando]=!0};c.Event.prototype={isDefaultPrevented:X,isPropagationStopped:X,isImmediatePropagationStopped:X,
preventDefault:function(){var a=this.originalEvent;this.isDefaultPrevented=pa;a&&(a.preventDefault?a.preventDefault():a.returnValue=!1)},stopPropagation:function(){var a=this.originalEvent;this.isPropagationStopped=pa;a&&(a.stopPropagation&&a.stopPropagation(),a.cancelBubble=!0)},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=pa;this.stopPropagation()}};c.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){c.event.special[a]={delegateType:b,bindType:b,handle:function(a){var d,
f=a.relatedTarget,g=a.handleObj;if(!f||f!==this&&!c.contains(this,f))a.type=g.origType,d=g.handler.apply(this,arguments),a.type=b;return d}}});c.support.submitBubbles||(c.event.special.submit={setup:function(){if(c.nodeName(this,"form"))return!1;c.event.add(this,"click._submit keypress._submit",function(a){a=a.target;(a=c.nodeName(a,"input")||c.nodeName(a,"button")?a.form:p)&&!c._data(a,"submitBubbles")&&(c.event.add(a,"submit._submit",function(a){a._submit_bubble=!0}),c._data(a,"submitBubbles",!0))})},
postDispatch:function(a){a._submit_bubble&&(delete a._submit_bubble,this.parentNode&&!a.isTrigger&&c.event.simulate("submit",this.parentNode,a,!0))},teardown:function(){if(c.nodeName(this,"form"))return!1;c.event.remove(this,"._submit")}});c.support.changeBubbles||(c.event.special.change={setup:function(){if(Ra.test(this.nodeName)){if("checkbox"===this.type||"radio"===this.type)c.event.add(this,"propertychange._change",function(a){"checked"===a.originalEvent.propertyName&&(this._just_changed=!0)}),
c.event.add(this,"click._change",function(a){this._just_changed&&!a.isTrigger&&(this._just_changed=!1);c.event.simulate("change",this,a,!0)});return!1}c.event.add(this,"beforeactivate._change",function(a){a=a.target;Ra.test(a.nodeName)&&!c._data(a,"changeBubbles")&&(c.event.add(a,"change._change",function(a){!this.parentNode||a.isSimulated||a.isTrigger||c.event.simulate("change",this.parentNode,a,!0)}),c._data(a,"changeBubbles",!0))})},handle:function(a){var b=a.target;if(this!==b||a.isSimulated||
a.isTrigger||"radio"!==b.type&&"checkbox"!==b.type)return a.handleObj.handler.apply(this,arguments)},teardown:function(){c.event.remove(this,"._change");return!Ra.test(this.nodeName)}});c.support.focusinBubbles||c.each({focus:"focusin",blur:"focusout"},function(a,b){var d=0,e=function(a){c.event.simulate(b,a.target,c.event.fix(a),!0)};c.event.special[b]={setup:function(){0===d++&&q.addEventListener(a,e,!0)},teardown:function(){0===--d&&q.removeEventListener(a,e,!0)}}});c.fn.extend({on:function(a,
b,d,e,f){var g,h;if("object"===typeof a){"string"!==typeof b&&(d=d||b,b=p);for(g in a)this.on(g,b,d,a[g],f);return this}null==d&&null==e?(e=b,d=b=p):null==e&&("string"===typeof b?(e=d,d=p):(e=d,d=b,b=p));if(!1===e)e=X;else if(!e)return this;1===f&&(h=e,e=function(a){c().off(a);return h.apply(this,arguments)},e.guid=h.guid||(h.guid=c.guid++));return this.each(function(){c.event.add(this,a,e,d,b)})},one:function(a,b,c,e){return this.on(a,b,c,e,1)},off:function(a,b,d){var e;if(a&&a.preventDefault&&a.handleObj)return e=
a.handleObj,c(a.delegateTarget).off(e.namespace?e.origType+"."+e.namespace:e.origType,e.selector,e.handler),this;if("object"===typeof a){for(e in a)this.off(e,b,a[e]);return this}if(!1===b||"function"===typeof b)d=b,b=p;!1===d&&(d=X);return this.each(function(){c.event.remove(this,a,d,b)})},bind:function(a,b,c){return this.on(a,null,b,c)},unbind:function(a,b){return this.off(a,null,b)},delegate:function(a,b,c,e){return this.on(b,a,c,e)},undelegate:function(a,b,c){return 1===arguments.length?this.off(a,
"**"):this.off(b,a||"**",c)},trigger:function(a,b){return this.each(function(){c.event.trigger(a,b,this)})},triggerHandler:function(a,b){var d=this[0];if(d)return c.event.trigger(a,b,d,!0)}});(function(a,b){function d(){var a,b=[];return a=function(c,d){b.push(c+=" ")>t.cacheLength&&delete a[b.shift()];return a[c]=d}}function e(a){a[x]=!0;return a}function f(a){var b=N.createElement("div");try{return a(b)}catch(C){return!1}finally{}}function g(a,b,c,d){var e,f,g,h,k;(b?b.ownerDocument||b:na)!==N&&
ta(b);b=b||N;c=c||[];if(!a||"string"!==typeof a)return c;if(1!==(h=b.nodeType)&&9!==h)return[];if(!y&&!d){if(e=oa.exec(a))if(g=e[1])if(9===h)if((f=b.getElementById(g))&&f.parentNode){if(f.id===g)return c.push(f),c}else return c;else{if(b.ownerDocument&&(f=b.ownerDocument.getElementById(g))&&xa(b,f)&&f.id===g)return c.push(f),c}else{if(e[2])return P.apply(c,Q.call(b.getElementsByTagName(a),0)),c;if((g=e[3])&&D.getByClassName&&b.getElementsByClassName)return P.apply(c,Q.call(b.getElementsByClassName(g),
0)),c}if(D.qsa&&!aa.test(a)){e=!0;f=x;g=b;k=9===h&&a;if(1===h&&"object"!==b.nodeName.toLowerCase()){h=n(a);(e=b.getAttribute("id"))?f=e.replace(ra,"\\$&"):b.setAttribute("id",f);f="[id='"+f+"'] ";for(g=h.length;g--;)h[g]=f+m(h[g]);g=da.test(a)&&b.parentNode||b;k=h.join(",")}if(k)try{return P.apply(c,Q.call(g.querySelectorAll(k),0)),c}catch(Vc){}finally{e||b.removeAttribute("id")}}}var u;a:{a=a.replace(T,"$1");f=n(a);if(!d&&1===f.length){e=f[0]=f[0].slice(0);if(2<e.length&&"ID"===(u=e[0]).type&&9===
b.nodeType&&!y&&t.relative[e[1].type]){b=t.find.ID(u.matches[0].replace(ia,ja),b)[0];if(!b){u=c;break a}a=a.slice(e.shift().value.length)}for(h=Z.needsContext.test(a)?0:e.length;h--;){u=e[h];if(t.relative[g=u.type])break;if(g=t.find[g])if(d=g(u.matches[0].replace(ia,ja),da.test(e[0].type)&&b.parentNode||b)){e.splice(h,1);a=d.length&&m(e);if(!a){P.apply(c,Q.call(d,0));u=c;break a}break}}}Sa(a,f)(d,b,y,c,da.test(a));u=c}return u}function h(a,b){var c=b&&a,d=c&&(~b.sourceIndex||-2147483648)-(~a.sourceIndex||
-2147483648);if(d)return d;if(c)for(;c=c.nextSibling;)if(c===b)return-1;return a?1:-1}function k(a){return function(b){return"input"===b.nodeName.toLowerCase()&&b.type===a}}function l(a){return function(b){var c=b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}}function p(a){return e(function(b){b=+b;return e(function(c,d){for(var e,f=a([],c.length,b),g=f.length;g--;)c[e=f[g]]&&(c[e]=!(d[e]=c[e]))})})}function n(a,b){var c,d,e,f,h,k,u;if(h=W[a+" "])return b?0:h.slice(0);h=a;
k=[];for(u=t.preFilter;h;){if(!c||(d=ga.exec(h)))d&&(h=h.slice(d[0].length)||h),k.push(e=[]);c=!1;if(d=ka.exec(h))c=d.shift(),e.push({value:c,type:d[0].replace(T," ")}),h=h.slice(c.length);for(f in t.filter)!(d=Z[f].exec(h))||u[f]&&!(d=u[f](d))||(c=d.shift(),e.push({value:c,type:f,matches:d}),h=h.slice(c.length));if(!c)break}return b?h.length:h?g.error(a):W(a,k).slice(0)}function m(a){for(var b=0,c=a.length,d="";b<c;b++)d+=a[b].value;return d}function r(a,b,c){var d=b.dir,e=c&&"parentNode"===d,f=
S++;return b.first?function(b,c,f){for(;b=b[d];)if(1===b.nodeType||e)return a(b,c,f)}:function(b,c,g){var h,k,u,C=E+" "+f;if(g)for(;b=b[d];){if((1===b.nodeType||e)&&a(b,c,g))return!0}else for(;b=b[d];)if(1===b.nodeType||e)if(u=b[x]||(b[x]={}),(k=u[d])&&k[0]===C){if(!0===(h=k[1])||h===F)return!0===h}else if(k=u[d]=[C],k[1]=a(b,c,g)||F,!0===k[1])return!0}}function q(a){return 1<a.length?function(b,c,d){for(var e=a.length;e--;)if(!a[e](b,c,d))return!1;return!0}:a[0]}function z(a,b,c,d,e){for(var f,g=
[],h=0,k=a.length,u=null!=b;h<k;h++)if(f=a[h])if(!c||c(f,d,e))g.push(f),u&&b.push(h);return g}function A(a,b,c,d,f,h){d&&!d[x]&&(d=A(d));f&&!f[x]&&(f=A(f,h));return e(function(e,h,k,u){var C,l,ha=[],m=[],p=h.length,K;if(!(K=e)){K=b||"*";for(var n=k.nodeType?[k]:k,r=[],wa=0,q=n.length;wa<q;wa++)g(K,n[wa],r);K=r}K=!a||!e&&b?K:z(K,ha,a,k,u);n=c?f||(e?a:p||d)?[]:h:K;c&&c(K,n,k,u);if(d)for(C=z(n,m),d(C,[],k,u),k=C.length;k--;)if(l=C[k])n[m[k]]=!(K[m[k]]=l);if(e){if(f||a){if(f){C=[];for(k=n.length;k--;)(l=
n[k])&&C.push(K[k]=l);f(null,n=[],C,u)}for(k=n.length;k--;)(l=n[k])&&-1<(C=f?V.call(e,l):ha[k])&&(e[C]=!(h[C]=l))}}else n=z(n===h?n.splice(p,n.length):n),f?f(null,h,n,u):P.apply(h,n)})}function H(a){var b,c,d,e=a.length,f=t.relative[a[0].type];c=f||t.relative[" "];for(var g=f?1:0,h=r(function(a){return a===b},c,!0),k=r(function(a){return-1<V.call(b,a)},c,!0),u=[function(a,c,d){return!f&&(d||c!==Da)||((b=c).nodeType?h(a,c,d):k(a,c,d))}];g<e;g++)if(c=t.relative[a[g].type])u=[r(q(u),c)];else{c=t.filter[a[g].type].apply(null,
a[g].matches);if(c[x]){for(d=++g;d<e&&!t.relative[a[d].type];d++);return A(1<g&&q(u),1<g&&m(a.slice(0,g-1)).replace(T,"$1"),c,g<d&&H(a.slice(g,d)),d<e&&H(a=a.slice(d)),d<e&&m(a))}u.push(c)}return q(u)}function G(a,b){var c=0,d=0<b.length,f=0<a.length,h=function(e,h,k,u,C){var l,ha,m=[],p=0,n="0",K=e&&[],r=null!=C,q=Da,wa=e||f&&t.find.TAG("*",C&&h.parentNode||h),v=E+=null==q?1:Math.random()||.1;r&&(Da=h!==N&&h,F=c);for(;null!=(C=wa[n]);n++){if(f&&C){for(l=0;ha=a[l++];)if(ha(C,h,k)){u.push(C);break}r&&
(E=v,F=++c)}d&&((C=!ha&&C)&&p--,e&&K.push(C))}p+=n;if(d&&n!==p){for(l=0;ha=b[l++];)ha(K,m,h,k);if(e){if(0<p)for(;n--;)K[n]||m[n]||(m[n]=ca.call(u));m=z(m)}P.apply(u,m);r&&!e&&0<m.length&&1<p+b.length&&g.uniqueSort(u)}r&&(E=v,Da=q);return K};return d?e(h):h}function w(){}var J,F,t,L,ya,Sa,ua,Da,ta,N,R,y,aa,va,I,xa,O,x="sizzle"+-new Date,na=a.document,D={},E=0,S=0,U=d(),W=d(),Y=d(),fa=typeof b,B=[],ca=B.pop,P=B.push,Q=B.slice,V=B.indexOf||function(a){for(var b=0,c=this.length;b<c;b++)if(this[b]===a)return b;
return-1},B="(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w#"),ba="\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)[\\x20\\t\\r\\n\\f]*(?:([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:(['\"])((?:\\\\.|[^\\\\])*?)\\3|("+B+")|)|)[\\x20\\t\\r\\n\\f]*\\]",X=":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\(((['\"])((?:\\\\.|[^\\\\])*?)\\3|((?:\\\\.|[^\\\\()[\\]]|"+ba.replace(3,8)+")*)|.*)\\)|)",T=RegExp("^[\\x20\\t\\r\\n\\f]+|((?:^|[^\\\\])(?:\\\\.)*)[\\x20\\t\\r\\n\\f]+$","g"),ga=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,
ka=/^[\x20\t\r\n\f]*([\x20\t\r\n\f>+~])[\x20\t\r\n\f]*/,la=new RegExp(X),ma=new RegExp("^"+B+"$"),Z={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,NAME:/^\[name=['"]?((?:\\.|[\w-]|[^\x00-\xa0])+)['"]?\]/,TAG:new RegExp("^("+"(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w*")+")"),ATTR:new RegExp("^"+ba),PSEUDO:new RegExp("^"+X),CHILD:/^:(only|first|last|nth|nth-last)-(child|of-type)(?:\([\x20\t\r\n\f]*(even|odd|(([+-]|)(\d*)n|)[\x20\t\r\n\f]*(?:([+-]|)[\x20\t\r\n\f]*(\d+)|))[\x20\t\r\n\f]*\)|)/i,
needsContext:/^[\x20\t\r\n\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\([\x20\t\r\n\f]*((?:-\d)?\d*)[\x20\t\r\n\f]*\)|)(?=[^-]|$)/i},da=/[\x20\t\r\n\f]*[+~]/,ea=/^[^{]+\{\s*\[native code/,oa=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,pa=/^(?:input|select|textarea|button)$/i,qa=/^h\d$/i,ra=/'|\\/g,sa=/\=[\x20\t\r\n\f]*([^'"\]]*)[\x20\t\r\n\f]*\]/g,ia=/\\([\da-fA-F]{1,6}[\x20\t\r\n\f]?|.)/g,ja=function(a,b){var c="0x"+b-65536;return c!==c?b:0>c?String.fromCharCode(c+65536):String.fromCharCode(c>>10|55296,
c&1023|56320)};try{Q.call(na.documentElement.childNodes,0)[0].nodeType}catch(u){Q=function(a){for(var b,c=[];b=this[a++];)c.push(b);return c}}ya=g.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};ta=g.setDocument=function(a){var c=a?a.ownerDocument||a:na;if(c===N||9!==c.nodeType||!c.documentElement)return N;N=c;R=c.documentElement;y=ya(c);D.tagNameNoComments=f(function(a){a.appendChild(c.createComment(""));return!a.getElementsByTagName("*").length});D.attributes=
f(function(a){a.innerHTML="<select></select>";a=typeof a.lastChild.getAttribute("multiple");return"boolean"!==a&&"string"!==a});D.getByClassName=f(function(a){a.innerHTML="<div class='hidden e'></div><div class='hidden'></div>";if(!a.getElementsByClassName||!a.getElementsByClassName("e").length)return!1;a.lastChild.className="e";return 2===a.getElementsByClassName("e").length});D.getByName=f(function(a){a.id=x+0;a.innerHTML="<a name='"+x+"'></a><div name='"+x+"'></div>";R.insertBefore(a,R.firstChild);
var b=c.getElementsByName&&c.getElementsByName(x).length===2+c.getElementsByName(x+0).length;D.getIdNotName=!c.getElementById(x);R.removeChild(a);return b});t.attrHandle=f(function(a){a.innerHTML="<a href='#'></a>";return a.firstChild&&typeof a.firstChild.getAttribute!==fa&&"#"===a.firstChild.getAttribute("href")})?{}:{href:function(a){return a.getAttribute("href",2)},type:function(a){return a.getAttribute("type")}};D.getIdNotName?(t.find.ID=function(a,b){if(typeof b.getElementById!==fa&&!y){var c=
b.getElementById(a);return c&&c.parentNode?[c]:[]}},t.filter.ID=function(a){var b=a.replace(ia,ja);return function(a){return a.getAttribute("id")===b}}):(t.find.ID=function(a,c){if(typeof c.getElementById!==fa&&!y){var d=c.getElementById(a);return d?d.id===a||typeof d.getAttributeNode!==fa&&d.getAttributeNode("id").value===a?[d]:b:[]}},t.filter.ID=function(a){var b=a.replace(ia,ja);return function(a){return(a=typeof a.getAttributeNode!==fa&&a.getAttributeNode("id"))&&a.value===b}});t.find.TAG=D.tagNameNoComments?
function(a,b){if(typeof b.getElementsByTagName!==fa)return b.getElementsByTagName(a)}:function(a,b){var c,d=[],e=0,f=b.getElementsByTagName(a);if("*"===a){for(;c=f[e++];)1===c.nodeType&&d.push(c);return d}return f};t.find.NAME=D.getByName&&function(a,b){if(typeof b.getElementsByName!==fa)return b.getElementsByName(name)};t.find.CLASS=D.getByClassName&&function(a,b){if(typeof b.getElementsByClassName!==fa&&!y)return b.getElementsByClassName(a)};va=[];aa=[":focus"];if(D.qsa=ea.test(c.querySelectorAll+
""))f(function(a){a.innerHTML="<select><option selected=''></option></select>";a.querySelectorAll("[selected]").length||aa.push("\\[[\\x20\\t\\r\\n\\f]*(?:checked|disabled|ismap|multiple|readonly|selected|value)");a.querySelectorAll(":checked").length||aa.push(":checked")}),f(function(a){a.innerHTML="<input type='hidden' i=''/>";a.querySelectorAll("[i^='']").length&&aa.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:\"\"|'')");a.querySelectorAll(":enabled").length||aa.push(":enabled",":disabled");a.querySelectorAll("*,:x");
aa.push(",.*:")});(D.matchesSelector=ea.test((I=R.matchesSelector||R.mozMatchesSelector||R.webkitMatchesSelector||R.oMatchesSelector||R.msMatchesSelector)+""))&&f(function(a){D.disconnectedMatch=I.call(a,"div");I.call(a,"[s!='']:x");va.push("!=",X)});aa=new RegExp(aa.join("|"));va=new RegExp(va.join("|"));xa=ea.test(R.contains+"")||R.compareDocumentPosition?function(a,b){var c=9===a.nodeType?a.documentElement:a,d=b&&b.parentNode;return a===d||!!(d&&1===d.nodeType&&(c.contains?c.contains(d):a.compareDocumentPosition&&
a.compareDocumentPosition(d)&16))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1};O=R.compareDocumentPosition?function(a,b){var d;return a===b?(ua=!0,0):(d=b.compareDocumentPosition&&a.compareDocumentPosition&&a.compareDocumentPosition(b))?d&1||a.parentNode&&11===a.parentNode.nodeType?a===c||xa(na,a)?-1:b===c||xa(na,b)?1:0:d&4?-1:1:a.compareDocumentPosition?-1:1}:function(a,b){var d,e=0;d=a.parentNode;var f=b.parentNode,g=[a],k=[b];if(a===b)return ua=!0,0;if(!d||!f)return a===
c?-1:b===c?1:d?-1:f?1:0;if(d===f)return h(a,b);for(d=a;d=d.parentNode;)g.unshift(d);for(d=b;d=d.parentNode;)k.unshift(d);for(;g[e]===k[e];)e++;return e?h(g[e],k[e]):g[e]===na?-1:k[e]===na?1:0};ua=!1;[0,0].sort(O);D.detectDuplicates=ua;return N};g.matches=function(a,b){return g(a,null,null,b)};g.matchesSelector=function(a,b){(a.ownerDocument||a)!==N&&ta(a);b=b.replace(sa,"='$1']");if(!(!D.matchesSelector||y||va&&va.test(b)||aa.test(b)))try{var c=I.call(a,b);if(c||D.disconnectedMatch||a.document&&11!==
a.document.nodeType)return c}catch(K){}return 0<g(b,N,null,[a]).length};g.contains=function(a,b){(a.ownerDocument||a)!==N&&ta(a);return xa(a,b)};g.attr=function(a,b){var c;(a.ownerDocument||a)!==N&&ta(a);y||(b=b.toLowerCase());return(c=t.attrHandle[b])?c(a):y||D.attributes?a.getAttribute(b):((c=a.getAttributeNode(b))||a.getAttribute(b))&&!0===a[b]?b:c&&c.specified?c.value:null};g.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};g.uniqueSort=function(a){var b,c=[],d=1,e=
0;ua=!D.detectDuplicates;a.sort(O);if(ua){for(;b=a[d];d++)b===a[d-1]&&(e=c.push(d));for(;e--;)a.splice(c[e],1)}return a};L=g.getText=function(a){var b,c="",d=0;b=a.nodeType;if(!b)for(;b=a[d];d++)c+=L(b);else if(1===b||9===b||11===b){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)c+=L(a)}else if(3===b||4===b)return a.nodeValue;return c};t=g.selectors={cacheLength:50,createPseudo:e,match:Z,find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},
"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=a[1].replace(ia,ja);a[3]=(a[4]||a[5]||"").replace(ia,ja);"~="===a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1].slice(0,3)?(a[3]||g.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&g.error(a[0]);return a},PSEUDO:function(a){var b,c=!a[5]&&a[2];if(Z.CHILD.test(a[0]))return null;a[4]?a[2]=
a[4]:c&&la.test(c)&&(b=n(c,!0))&&(b=c.indexOf(")",c.length-b)-c.length)&&(a[0]=a[0].slice(0,b),a[2]=c.slice(0,b));return a.slice(0,3)}},filter:{TAG:function(a){if("*"===a)return function(){return!0};a=a.replace(ia,ja).toLowerCase();return function(b){return b.nodeName&&b.nodeName.toLowerCase()===a}},CLASS:function(a){var b=U[a+" "];return b||(b=new RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"),U(a,function(a){return b.test(a.className||typeof a.getAttribute!==fa&&a.getAttribute("class")||
"")}))},ATTR:function(a,b,c){return function(d){d=g.attr(d,a);if(null==d)return"!="===b;if(!b)return!0;d+="";return"="===b?d===c:"!="===b?d!==c:"^="===b?c&&0===d.indexOf(c):"*="===b?c&&-1<d.indexOf(c):"$="===b?c&&d.slice(-c.length)===c:"~="===b?-1<(" "+d+" ").indexOf(c):"|="===b?d===c||d.slice(0,c.length+1)===c+"-":!1}},CHILD:function(a,b,c,d,e){var f="nth"!==a.slice(0,3),g="last"!==a.slice(-4),h="of-type"===b;return 1===d&&0===e?function(a){return!!a.parentNode}:function(b,c,k){var l,m,p,u,n;c=f!==
g?"nextSibling":"previousSibling";var r=b.parentNode,q=h&&b.nodeName.toLowerCase();k=!k&&!h;if(r){if(f){for(;c;){for(m=b;m=m[c];)if(h?m.nodeName.toLowerCase()===q:1===m.nodeType)return!1;n=c="only"===a&&!n&&"nextSibling"}return!0}n=[g?r.firstChild:r.lastChild];if(g&&k)for(k=r[x]||(r[x]={}),l=k[a]||[],u=l[0]===E&&l[1],p=l[0]===E&&l[2],m=u&&r.childNodes[u];m=++u&&m&&m[c]||(p=u=0)||n.pop();){if(1===m.nodeType&&++p&&m===b){k[a]=[E,u,p];break}}else if(k&&(l=(b[x]||(b[x]={}))[a])&&l[0]===E)p=l[1];else for(;(m=
++u&&m&&m[c]||(p=u=0)||n.pop())&&((h?m.nodeName.toLowerCase()!==q:1!==m.nodeType)||!++p||(k&&((m[x]||(m[x]={}))[a]=[E,p]),m!==b)););p-=e;return p===d||0===p%d&&0<=p/d}}},PSEUDO:function(a,b){var c,d=t.pseudos[a]||t.setFilters[a.toLowerCase()]||g.error("unsupported pseudo: "+a);return d[x]?d(b):1<d.length?(c=[a,a,"",b],t.setFilters.hasOwnProperty(a.toLowerCase())?e(function(a,c){for(var e,f=d(a,b),g=f.length;g--;)e=V.call(a,f[g]),a[e]=!(c[e]=f[g])}):function(a){return d(a,0,c)}):d}},pseudos:{not:e(function(a){var b=
[],c=[],d=Sa(a.replace(T,"$1"));return d[x]?e(function(a,b,c,e){e=d(a,null,e,[]);for(var f=a.length;f--;)if(c=e[f])a[f]=!(b[f]=c)}):function(a,e,f){b[0]=a;d(b,null,f,c);return!c.pop()}}),has:e(function(a){return function(b){return 0<g(a,b).length}}),contains:e(function(a){return function(b){return-1<(b.textContent||b.innerText||L(b)).indexOf(a)}}),lang:e(function(a){ma.test(a||"")||g.error("unsupported lang: "+a);a=a.replace(ia,ja).toLowerCase();return function(b){var c;do if(c=y?b.getAttribute("xml:lang")||
b.getAttribute("lang"):b.lang)return c=c.toLowerCase(),c===a||0===c.indexOf(a+"-");while((b=b.parentNode)&&1===b.nodeType);return!1}}),target:function(b){var c=a.location&&a.location.hash;return c&&c.slice(1)===b.id},root:function(a){return a===R},focus:function(a){return a===N.activeElement&&(!N.hasFocus||N.hasFocus())&&!!(a.type||a.href||~a.tabIndex)},enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===
b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;return!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if("@"<a.nodeName||3===a.nodeType||4===a.nodeType)return!1;return!0},parent:function(a){return!t.pseudos.empty(a)},header:function(a){return qa.test(a.nodeName)},input:function(a){return pa.test(a.nodeName)},button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},text:function(a){var b;
return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==(b=a.getAttribute("type"))||b.toLowerCase()===a.type)},first:p(function(){return[0]}),last:p(function(a,b){return[b-1]}),eq:p(function(a,b,c){return[0>c?c+b:c]}),even:p(function(a,b){for(var c=0;c<b;c+=2)a.push(c);return a}),odd:p(function(a,b){for(var c=1;c<b;c+=2)a.push(c);return a}),lt:p(function(a,b,c){for(b=0>c?c+b:c;0<=--b;)a.push(b);return a}),gt:p(function(a,b,c){for(c=0>c?c+b:c;++c<b;)a.push(c);return a})}};for(J in{radio:!0,
checkbox:!0,file:!0,password:!0,image:!0})t.pseudos[J]=k(J);for(J in{submit:!0,reset:!0})t.pseudos[J]=l(J);Sa=g.compile=function(a,b){var c,d=[],e=[],f=Y[a+" "];if(!f){b||(b=n(a));for(c=b.length;c--;)f=H(b[c]),f[x]?d.push(f):e.push(f);f=Y(a,G(e,d))}return f};t.pseudos.nth=t.pseudos.eq;t.filters=w.prototype=t.pseudos;t.setFilters=new w;ta();g.attr=c.attr;c.find=g;c.expr=g.selectors;c.expr[":"]=c.expr.pseudos;c.unique=g.uniqueSort;c.text=g.getText;c.isXMLDoc=g.isXML;c.contains=g.contains})(n);var xc=
/Until$/,yc=/^(?:parents|prev(?:Until|All))/,Xb=/^.[^:#\[\.,]*$/,Gb=c.expr.match.needsContext,zc={children:!0,contents:!0,next:!0,prev:!0};c.fn.extend({find:function(a){var b,d,e,f=this.length;if("string"!==typeof a)return e=this,this.pushStack(c(a).filter(function(){for(b=0;b<f;b++)if(c.contains(e[b],this))return!0}));d=[];for(b=0;b<f;b++)c.find(a,this[b],d);d=this.pushStack(1<f?c.unique(d):d);d.selector=(this.selector?this.selector+" ":"")+a;return d},has:function(a){var b,d=c(a,this),e=d.length;
return this.filter(function(){for(b=0;b<e;b++)if(c.contains(this,d[b]))return!0})},not:function(a){return this.pushStack(cb(this,a,!1))},filter:function(a){return this.pushStack(cb(this,a,!0))},is:function(a){return!!a&&("string"===typeof a?Gb.test(a)?0<=c(a,this.context).index(this[0]):0<c.filter(a,this).length:0<this.filter(a).length)},closest:function(a,b){for(var d,e=0,f=this.length,g=[],h=Gb.test(a)||"string"!==typeof a?c(a,b||this.context):0;e<f;e++)for(d=this[e];d&&d.ownerDocument&&d!==b&&
11!==d.nodeType;){if(h?-1<h.index(d):c.find.matchesSelector(d,a)){g.push(d);break}d=d.parentNode}return this.pushStack(1<g.length?c.unique(g):g)},index:function(a){return a?"string"===typeof a?c.inArray(this[0],c(a)):c.inArray(a.jquery?a[0]:a,this):this[0]&&this[0].parentNode?this.first().prevAll().length:-1},add:function(a,b){var d="string"===typeof a?c(a,b):c.makeArray(a&&a.nodeType?[a]:a),d=c.merge(this.get(),d);return this.pushStack(c.unique(d))},addBack:function(a){return this.add(null==a?this.prevObject:
this.prevObject.filter(a))}});c.fn.andSelf=c.fn.addBack;c.each({parent:function(a){return(a=a.parentNode)&&11!==a.nodeType?a:null},parents:function(a){return c.dir(a,"parentNode")},parentsUntil:function(a,b,d){return c.dir(a,"parentNode",d)},next:function(a){return bb(a,"nextSibling")},prev:function(a){return bb(a,"previousSibling")},nextAll:function(a){return c.dir(a,"nextSibling")},prevAll:function(a){return c.dir(a,"previousSibling")},nextUntil:function(a,b,d){return c.dir(a,"nextSibling",d)},
prevUntil:function(a,b,d){return c.dir(a,"previousSibling",d)},siblings:function(a){return c.sibling((a.parentNode||{}).firstChild,a)},children:function(a){return c.sibling(a.firstChild)},contents:function(a){return c.nodeName(a,"iframe")?a.contentDocument||a.contentWindow.document:c.merge([],a.childNodes)}},function(a,b){c.fn[a]=function(d,e){var f=c.map(this,b,d);xc.test(a)||(e=d);e&&"string"===typeof e&&(f=c.filter(e,f));f=1<this.length&&!zc[a]?c.unique(f):f;1<this.length&&yc.test(a)&&(f=f.reverse());
return this.pushStack(f)}});c.extend({filter:function(a,b,d){d&&(a=":not("+a+")");return 1===b.length?c.find.matchesSelector(b[0],a)?[b[0]]:[]:c.find.matches(a,b)},dir:function(a,b,d){var e=[];for(a=a[b];a&&9!==a.nodeType&&(d===p||1!==a.nodeType||!c(a).is(d));)1===a.nodeType&&e.push(a),a=a[b];return e},sibling:function(a,b){for(var c=[];a;a=a.nextSibling)1===a.nodeType&&a!==b&&c.push(a);return c}});var eb="abbr|article|aside|audio|bdi|canvas|data|datalist|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video",
Ac=/ jQuery\d+="(?:null|\d+)"/g,Hb=new RegExp("<(?:"+eb+")[\\s/>]","i"),Ta=/^\s+/,Ib=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/gi,Jb=/<([\w:]+)/,Kb=/<tbody/i,Bc=/<|&#?\w+;/,Cc=/<(?:script|style|link)/i,Ha=/^(?:checkbox|radio)$/i,Dc=/checked\s*(?:[^=]|=\s*.checked.)/i,Lb=/^$|\/(?:java|ecma)script/i,Zb=/^true\/(.*)/,Ec=/^\s*<!(?:\[CDATA\[|--)|(?:\]\]|--)>\s*$/g,w={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>","</fieldset>"],area:[1,"<map>",
"</map>"],param:[1,"<object>","</object>"],thead:[1,"<table>","</table>"],tr:[2,"<table><tbody>","</tbody></table>"],col:[2,"<table><tbody></tbody><colgroup>","</colgroup></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],_default:c.support.htmlSerialize?[0,"",""]:[1,"X<div>","</div>"]},Ua=db(q).appendChild(q.createElement("div"));w.optgroup=w.option;w.tbody=w.tfoot=w.colgroup=w.caption=w.thead;w.th=w.td;c.fn.extend({text:function(a){return c.access(this,function(a){return a===p?c.text(this):
this.empty().append((this[0]&&this[0].ownerDocument||q).createTextNode(a))},null,a,arguments.length)},wrapAll:function(a){if(c.isFunction(a))return this.each(function(b){c(this).wrapAll(a.call(this,b))});if(this[0]){var b=c(a,this[0].ownerDocument).eq(0).clone(!0);this[0].parentNode&&b.insertBefore(this[0]);b.map(function(){for(var a=this;a.firstChild&&1===a.firstChild.nodeType;)a=a.firstChild;return a}).append(this)}return this},wrapInner:function(a){return c.isFunction(a)?this.each(function(b){c(this).wrapInner(a.call(this,
b))}):this.each(function(){var b=c(this),d=b.contents();d.length?d.wrapAll(a):b.append(a)})},wrap:function(a){var b=c.isFunction(a);return this.each(function(d){c(this).wrapAll(b?a.call(this,d):a)})},unwrap:function(){return this.parent().each(function(){c.nodeName(this,"body")||c(this).replaceWith(this.childNodes)}).end()},append:function(){return this.domManip(arguments,!0,function(a){1!==this.nodeType&&11!==this.nodeType&&9!==this.nodeType||this.appendChild(a)})},prepend:function(){return this.domManip(arguments,
!0,function(a){1!==this.nodeType&&11!==this.nodeType&&9!==this.nodeType||this.insertBefore(a,this.firstChild)})},before:function(){return this.domManip(arguments,!1,function(a){this.parentNode&&this.parentNode.insertBefore(a,this)})},after:function(){return this.domManip(arguments,!1,function(a){this.parentNode&&this.parentNode.insertBefore(a,this.nextSibling)})},remove:function(a,b){for(var d,e=0;null!=(d=this[e]);e++)if(!a||0<c.filter(a,[d]).length)b||1!==d.nodeType||c.cleanData(z(d)),d.parentNode&&
(b&&c.contains(d.ownerDocument,d)&&Ga(z(d,"script")),d.parentNode.removeChild(d));return this},empty:function(){for(var a,b=0;null!=(a=this[b]);b++){for(1===a.nodeType&&c.cleanData(z(a,!1));a.firstChild;)a.removeChild(a.firstChild);a.options&&c.nodeName(a,"select")&&(a.options.length=0)}return this},clone:function(a,b){a=null==a?!1:a;b=null==b?a:b;return this.map(function(){return c.clone(this,a,b)})},html:function(a){return c.access(this,function(a){var b=this[0]||{},e=0,f=this.length;if(a===p)return 1===
b.nodeType?b.innerHTML.replace(Ac,""):p;if(!("string"!==typeof a||Cc.test(a)||!c.support.htmlSerialize&&Hb.test(a)||!c.support.leadingWhitespace&&Ta.test(a)||w[(Jb.exec(a)||["",""])[1].toLowerCase()])){a=a.replace(Ib,"<$1></$2>");try{for(;e<f;e++)b=this[e]||{},1===b.nodeType&&(c.cleanData(z(b,!1)),b.innerHTML=a);b=0}catch(g){}}b&&this.empty().append(a)},null,a,arguments.length)},replaceWith:function(a){c.isFunction(a)||"string"===typeof a||(a=c(a).not(this).detach());return this.domManip([a],!0,function(a){var b=
this.nextSibling,e=this.parentNode;e&&(c(this).remove(),e.insertBefore(a,b))})},detach:function(a){return this.remove(a,!0)},domManip:function(a,b,d){a=yb.apply([],a);var e,f,g,h,k=0,l=this.length,n=this,q=l-1,m=a[0],r=c.isFunction(m);if(r||!(1>=l||"string"!==typeof m||c.support.checkClone)&&Dc.test(m))return this.each(function(c){var e=n.eq(c);r&&(a[0]=m.call(this,c,b?e.html():p));e.domManip(a,b,d)});if(l&&(h=c.buildFragment(a,this[0].ownerDocument,!1,this),e=h.firstChild,1===h.childNodes.length&&
(h=e),e)){b=b&&c.nodeName(e,"tr");g=c.map(z(h,"script"),fb);for(f=g.length;k<l;k++)e=h,k!==q&&(e=c.clone(e,!0,!0),f&&c.merge(g,z(e,"script"))),d.call(b&&c.nodeName(this[k],"table")?Yb(this[k],"tbody"):this[k],e,k);if(f)for(h=g[g.length-1].ownerDocument,c.map(g,gb),k=0;k<f;k++)e=g[k],Lb.test(e.type||"")&&!c._data(e,"globalEval")&&c.contains(h,e)&&(e.src?c.ajax({url:e.src,type:"GET",dataType:"script",async:!1,global:!1,"throws":!0}):c.globalEval((e.text||e.textContent||e.innerHTML||"").replace(Ec,"")));
h=e=null}return this}});c.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){c.fn[a]=function(a){for(var d=0,f=[],g=c(a),h=g.length-1;d<=h;d++)a=d===h?this:this.clone(!0),c(g[d])[b](a),La.apply(f,a.get());return this.pushStack(f)}});c.extend({clone:function(a,b,d){var e,f,g,h,k,l=c.contains(a.ownerDocument,a);c.support.html5Clone||c.isXMLDoc(a)||!Hb.test("<"+a.nodeName+">")?g=a.cloneNode(!0):(Ua.innerHTML=a.outerHTML,Ua.removeChild(g=
Ua.firstChild));if(!(c.support.noCloneEvent&&c.support.noCloneChecked||1!==a.nodeType&&11!==a.nodeType||c.isXMLDoc(a)))for(e=z(g),k=z(a),h=0;null!=(f=k[h]);++h)if(e[h]){var p=void 0,n,m=f,r=e[h];if(1===r.nodeType){n=r.nodeName.toLowerCase();if(!c.support.noCloneEvent&&r[c.expando]){f=c._data(r);for(p in f.events)c.removeEvent(r,p,f.handle);r.removeAttribute(c.expando)}if("script"===n&&r.text!==m.text)fb(r).text=m.text,gb(r);else if("object"===n)r.parentNode&&(r.outerHTML=m.outerHTML),c.support.html5Clone&&
m.innerHTML&&!c.trim(r.innerHTML)&&(r.innerHTML=m.innerHTML);else if("input"===n&&Ha.test(m.type))r.defaultChecked=r.checked=m.checked,r.value!==m.value&&(r.value=m.value);else if("option"===n)r.defaultSelected=r.selected=m.defaultSelected;else if("input"===n||"textarea"===n)r.defaultValue=m.defaultValue}}if(b)if(d)for(k=k||z(a),e=e||z(g),h=0;null!=(f=k[h]);h++)hb(f,e[h]);else hb(a,g);e=z(g,"script");0<e.length&&Ga(e,!l&&z(a,"script"));return g},buildFragment:function(a,b,d,e){for(var f,g,h,k,l,p,
n=a.length,m=db(b),r=[],q=0;q<n;q++)if((g=a[q])||0===g)if("object"===c.type(g))c.merge(r,g.nodeType?[g]:g);else if(Bc.test(g)){h=h||m.appendChild(b.createElement("div"));k=(Jb.exec(g)||["",""])[1].toLowerCase();p=w[k]||w._default;h.innerHTML=p[1]+g.replace(Ib,"<$1></$2>")+p[2];for(f=p[0];f--;)h=h.lastChild;!c.support.leadingWhitespace&&Ta.test(g)&&r.push(b.createTextNode(Ta.exec(g)[0]));if(!c.support.tbody)for(f=(g="table"!==k||Kb.test(g)?"<table>"!==p[1]||Kb.test(g)?0:h:h.firstChild)&&g.childNodes.length;f--;)c.nodeName(l=
g.childNodes[f],"tbody")&&!l.childNodes.length&&g.removeChild(l);c.merge(r,h.childNodes);for(h.textContent="";h.firstChild;)h.removeChild(h.firstChild);h=m.lastChild}else r.push(b.createTextNode(g));h&&m.removeChild(h);c.support.appendChecked||c.grep(z(r,"input"),$b);for(q=0;g=r[q++];)if(!e||-1===c.inArray(g,e))if(a=c.contains(g.ownerDocument,g),h=z(m.appendChild(g),"script"),a&&Ga(h),d)for(f=0;g=h[f++];)Lb.test(g.type||"")&&d.push(g);return m},cleanData:function(a,b){for(var d,e,f,g,h=0,k=c.expando,
l=c.cache,p=c.support.deleteExpando,n=c.event.special;null!=(d=a[h]);h++)if(b||c.acceptData(d))if(g=(f=d[k])&&l[f]){if(g.events)for(e in g.events)n[e]?c.event.remove(d,e):c.removeEvent(d,e,g.handle);l[f]&&(delete l[f],p?delete d[k]:typeof d.removeAttribute!==O?d.removeAttribute(k):d[k]=null,ba.push(f))}}});var Z,B,ca,Va=/alpha\([^)]*\)/i,Fc=/opacity\s*=\s*([^)]*)/,Gc=/^(top|right|bottom|left)$/,Hc=/^(none|table(?!-c[ea]).+)/,Mb=/^margin/,ac=new RegExp("^("+Ba+")(.*)$","i"),qa=new RegExp("^("+Ba+")(?!px)[a-z%]+$",
"i"),Ic=new RegExp("^([+-])=("+Ba+")","i"),pb={BODY:"block"},Jc={position:"absolute",visibility:"hidden",display:"block"},Nb={letterSpacing:0,fontWeight:400},Y=["Top","Right","Bottom","Left"],jb=["Webkit","O","Moz","ms"];c.fn.extend({css:function(a,b){return c.access(this,function(a,b,f){var d,e={},k=0;if(c.isArray(b)){d=B(a);for(f=b.length;k<f;k++)e[b[k]]=c.css(a,b[k],!1,d);return e}return f!==p?c.style(a,b,f):c.css(a,b)},a,b,1<arguments.length)},show:function(){return kb(this,!0)},hide:function(){return kb(this)},
toggle:function(a){var b="boolean"===typeof a;return this.each(function(){(b?a:ma(this))?c(this).show():c(this).hide()})}});c.extend({cssHooks:{opacity:{get:function(a,b){if(b){var c=ca(a,"opacity");return""===c?"1":c}}}},cssNumber:{columnCount:!0,fillOpacity:!0,fontWeight:!0,lineHeight:!0,opacity:!0,orphans:!0,widows:!0,zIndex:!0,zoom:!0},cssProps:{"float":c.support.cssFloat?"cssFloat":"styleFloat"},style:function(a,b,d,e){if(a&&3!==a.nodeType&&8!==a.nodeType&&a.style){var f,g,h,k=c.camelCase(b),
l=a.style;b=c.cssProps[k]||(c.cssProps[k]=ib(l,k));h=c.cssHooks[b]||c.cssHooks[k];if(d!==p){if(g=typeof d,"string"===g&&(f=Ic.exec(d))&&(d=(f[1]+1)*f[2]+parseFloat(c.css(a,b)),g="number"),!(null==d||"number"===g&&isNaN(d)||("number"!==g||c.cssNumber[k]||(d+="px"),c.support.clearCloneStyle||""!==d||0!==b.indexOf("background")||(l[b]="inherit"),h&&"set"in h&&(d=h.set(a,d,e))===p)))try{l[b]=d}catch(v){}}else return h&&"get"in h&&(f=h.get(a,!1,e))!==p?f:l[b]}},css:function(a,b,d,e){var f,g;g=c.camelCase(b);
b=c.cssProps[g]||(c.cssProps[g]=ib(a.style,g));(g=c.cssHooks[b]||c.cssHooks[g])&&"get"in g&&(f=g.get(a,!0,d));f===p&&(f=ca(a,b,e));"normal"===f&&b in Nb&&(f=Nb[b]);return""===d||d?(a=parseFloat(f),!0===d||c.isNumeric(a)?a||0:f):f},swap:function(a,b,c,e){var d,g={};for(d in b)g[d]=a.style[d],a.style[d]=b[d];c=c.apply(a,e||[]);for(d in b)a.style[d]=g[d];return c}});n.getComputedStyle?(B=function(a){return n.getComputedStyle(a,null)},ca=function(a,b,d){var e,f=(d=d||B(a))?d.getPropertyValue(b)||d[b]:
p,g=a.style;d&&(""!==f||c.contains(a.ownerDocument,a)||(f=c.style(a,b)),qa.test(f)&&Mb.test(b)&&(a=g.width,b=g.minWidth,e=g.maxWidth,g.minWidth=g.maxWidth=g.width=f,f=d.width,g.width=a,g.minWidth=b,g.maxWidth=e));return f}):q.documentElement.currentStyle&&(B=function(a){return a.currentStyle},ca=function(a,b,c){var d,f,g=(c=c||B(a))?c[b]:p,h=a.style;null==g&&h&&h[b]&&(g=h[b]);if(qa.test(g)&&!Gc.test(b)){c=h.left;if(f=(d=a.runtimeStyle)&&d.left)d.left=a.currentStyle.left;h.left="fontSize"===b?"1em":
g;g=h.pixelLeft+"px";h.left=c;f&&(d.left=f)}return""===g?"auto":g});c.each(["height","width"],function(a,b){c.cssHooks[b]={get:function(a,e,f){if(e)return 0===a.offsetWidth&&Hc.test(c.css(a,"display"))?c.swap(a,Jc,function(){return ob(a,b,f)}):ob(a,b,f)},set:function(a,e,f){var d=f&&B(a);return mb(a,e,f?nb(a,b,f,c.support.boxSizing&&"border-box"===c.css(a,"boxSizing",!1,d),d):0)}}});c.support.opacity||(c.cssHooks.opacity={get:function(a,b){return Fc.test((b&&a.currentStyle?a.currentStyle.filter:a.style.filter)||
"")?.01*parseFloat(RegExp.$1)+"":b?"1":""},set:function(a,b){var d=a.style,e=a.currentStyle,f=c.isNumeric(b)?"alpha(opacity="+100*b+")":"",g=e&&e.filter||d.filter||"";d.zoom=1;if((1<=b||""===b)&&""===c.trim(g.replace(Va,""))&&d.removeAttribute&&(d.removeAttribute("filter"),""===b||e&&!e.filter))return;d.filter=Va.test(g)?g.replace(Va,f):g+" "+f}});c(function(){c.support.reliableMarginRight||(c.cssHooks.marginRight={get:function(a,b){if(b)return c.swap(a,{display:"inline-block"},ca,[a,"marginRight"])}});
!c.support.pixelPosition&&c.fn.position&&c.each(["top","left"],function(a,b){c.cssHooks[b]={get:function(a,e){if(e)return e=ca(a,b),qa.test(e)?c(a).position()[b]+"px":e}}})});c.expr&&c.expr.filters&&(c.expr.filters.hidden=function(a){return 0>=a.offsetWidth&&0>=a.offsetHeight||!c.support.reliableHiddenOffsets&&"none"===(a.style&&a.style.display||c.css(a,"display"))},c.expr.filters.visible=function(a){return!c.expr.filters.hidden(a)});c.each({margin:"",padding:"",border:"Width"},function(a,b){c.cssHooks[a+
b]={expand:function(c){var d=0,f={};for(c="string"===typeof c?c.split(" "):[c];4>d;d++)f[a+Y[d]+b]=c[d]||c[d-2]||c[0];return f}};Mb.test(a)||(c.cssHooks[a+b].set=mb)});var Kc=/%20/g,bc=/\[\]$/,Ob=/\r?\n/g,Lc=/^(?:submit|button|image|reset|file)$/i,Mc=/^(?:input|select|textarea|keygen)/i;c.fn.extend({serialize:function(){return c.param(this.serializeArray())},serializeArray:function(){return this.map(function(){var a=c.prop(this,"elements");return a?c.makeArray(a):this}).filter(function(){var a=this.type;
return this.name&&!c(this).is(":disabled")&&Mc.test(this.nodeName)&&!Lc.test(a)&&(this.checked||!Ha.test(a))}).map(function(a,b){var d=c(this).val();return null==d?null:c.isArray(d)?c.map(d,function(a){return{name:b.name,value:a.replace(Ob,"\r\n")}}):{name:b.name,value:d.replace(Ob,"\r\n")}}).get()}});c.param=function(a,b){var d,e=[],f=function(a,b){b=c.isFunction(b)?b():null==b?"":b;e[e.length]=encodeURIComponent(a)+"="+encodeURIComponent(b)};b===p&&(b=c.ajaxSettings&&c.ajaxSettings.traditional);
if(c.isArray(a)||a.jquery&&!c.isPlainObject(a))c.each(a,function(){f(this.name,this.value)});else for(d in a)Ia(d,a[d],b,f);return e.join("&").replace(Kc,"+")};c.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error contextmenu".split(" "),function(a,b){c.fn[b]=function(a,c){return 0<arguments.length?this.on(b,null,a,c):this.trigger(b)}});c.fn.hover=function(a,
b){return this.mouseenter(a).mouseleave(b||a)};var V,W,Wa=c.now(),Xa=/\?/,Nc=/#.*$/,Pb=/([?&])_=[^&]*/,Oc=/^(.*?):[ \t]*([^\r\n]*)\r?$/mg,Pc=/^(?:GET|HEAD)$/,Qc=/^\/\//,Qb=/^([\w.+-]+:)(?:\/\/([^\/?#:]*)(?::(\d+)|)|)/,Rb=c.fn.load,Sb={},Ja={},Tb="*/".concat("*");try{W=ec.href}catch(a){W=q.createElement("a"),W.href="",W=W.href}V=Qb.exec(W.toLowerCase())||[];c.fn.load=function(a,b,d){if("string"!==typeof a&&Rb)return Rb.apply(this,arguments);var e,f,g,h=this,k=a.indexOf(" ");0<=k&&(e=a.slice(k,a.length),
a=a.slice(0,k));c.isFunction(b)?(d=b,b=p):b&&"object"===typeof b&&(g="POST");0<h.length&&c.ajax({url:a,type:g,dataType:"html",data:b}).done(function(a){f=arguments;h.html(e?c("<div>").append(c.parseHTML(a)).find(e):a)}).complete(d&&function(a,b){h.each(d,f||[a.responseText,b,a])});return this};c.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){c.fn[b]=function(a){return this.on(b,a)}});c.each(["get","post"],function(a,b){c[b]=function(a,e,f,g){c.isFunction(e)&&
(g=g||f,f=e,e=p);return c.ajax({url:a,type:b,dataType:g,data:e,success:f})}});c.extend({active:0,lastModified:{},etag:{},ajaxSettings:{url:W,type:"GET",isLocal:/^(?:about|app|app-storage|.+-extension|file|res|widget):$/.test(V[1]),global:!0,processData:!0,async:!0,contentType:"application/x-www-form-urlencoded; charset=UTF-8",accepts:{"*":Tb,text:"text/plain",html:"text/html",xml:"application/xml, text/xml",json:"application/json, text/javascript"},contents:{xml:/xml/,html:/html/,json:/json/},responseFields:{xml:"responseXML",
text:"responseText"},converters:{"* text":n.String,"text html":!0,"text json":c.parseJSON,"text xml":c.parseXML},flatOptions:{url:!0,context:!0}},ajaxSetup:function(a,b){return b?Ka(Ka(a,c.ajaxSettings),b):Ka(c.ajaxSettings,a)},ajaxPrefilter:rb(Sb),ajaxTransport:rb(Ja),ajax:function(a,b){function d(a,b,d,e){var f,q,v,L,y=b;if(2!==J){J=2;k&&clearTimeout(k);n=p;h=e||"";t.readyState=0<a?4:0;if(d){L=m;e=t;var M,B,I,w,G=L.contents,x=L.dataTypes,ya=L.responseFields;for(w in ya)w in d&&(e[ya[w]]=d[w]);for(;"*"===
x[0];)x.shift(),B===p&&(B=L.mimeType||e.getResponseHeader("Content-Type"));if(B)for(w in G)if(G[w]&&G[w].test(B)){x.unshift(w);break}if(x[0]in d)I=x[0];else{for(w in d){if(!x[0]||L.converters[w+" "+x[0]]){I=w;break}M||(M=w)}I=I||M}I?(I!==x[0]&&x.unshift(I),L=d[I]):L=void 0}if(200<=a&&300>a||304===a)if(m.ifModified&&((d=t.getResponseHeader("Last-Modified"))&&(c.lastModified[g]=d),(d=t.getResponseHeader("etag"))&&(c.etag[g]=d)),204===a)f=!0,y="nocontent";else if(304===a)f=!0,y="notmodified";else{a:{q=
m;v=L;var D,E,y={};M=0;B=q.dataTypes.slice();I=B[0];q.dataFilter&&(v=q.dataFilter(v,q.dataType));if(B[1])for(E in q.converters)y[E.toLowerCase()]=q.converters[E];for(;d=B[++M];)if("*"!==d){if("*"!==I&&I!==d){E=y[I+" "+d]||y["* "+d];if(!E)for(D in y)if(f=D.split(" "),f[1]===d&&(E=y[I+" "+f[0]]||y["* "+f[0]])){!0===E?E=y[D]:!0!==y[D]&&(d=f[0],B.splice(M--,0,d));break}if(!0!==E)if(E&&q["throws"])v=E(v);else try{v=E(v)}catch(wc){f={state:"parsererror",error:E?wc:"No conversion from "+I+" to "+d};break a}}I=
d}f={state:"success",data:v}}y=f.state;q=f.data;v=f.error;f=!v}else if(v=y,a||!y)y="error",0>a&&(a=0);t.status=a;t.statusText=(b||y)+"";f?A.resolveWith(r,[q,y,t]):A.rejectWith(r,[t,y,v]);t.statusCode(F);F=p;l&&z.trigger(f?"ajaxSuccess":"ajaxError",[t,m,f?q:v]);H.fireWith(r,[t,y]);l&&(z.trigger("ajaxComplete",[t,m]),--c.active||c.event.trigger("ajaxStop"))}}"object"===typeof a&&(b=a,a=p);b=b||{};var e,f,g,h,k,l,n,q,m=c.ajaxSetup({},b),r=m.context||m,z=m.context&&(r.nodeType||r.jquery)?c(r):c.event,
A=c.Deferred(),H=c.Callbacks("once memory"),F=m.statusCode||{},B={},w={},J=0,G="canceled",t={readyState:0,getResponseHeader:function(a){var b;if(2===J){if(!q)for(q={};b=Oc.exec(h);)q[b[1].toLowerCase()]=b[2];b=q[a.toLowerCase()]}return null==b?null:b},getAllResponseHeaders:function(){return 2===J?h:null},setRequestHeader:function(a,b){var c=a.toLowerCase();J||(a=w[c]=w[c]||a,B[a]=b);return this},overrideMimeType:function(a){J||(m.mimeType=a);return this},statusCode:function(a){var b;if(a)if(2>J)for(b in a)F[b]=
[F[b],a[b]];else t.always(a[t.status]);return this},abort:function(a){a=a||G;n&&n.abort(a);d(0,a);return this}};A.promise(t).complete=H.add;t.success=t.done;t.error=t.fail;m.url=((a||m.url||W)+"").replace(Nc,"").replace(Qc,V[1]+"//");m.type=b.method||b.type||m.method||m.type;m.dataTypes=c.trim(m.dataType||"*").toLowerCase().match(S)||[""];null==m.crossDomain&&(e=Qb.exec(m.url.toLowerCase()),m.crossDomain=!(!e||e[1]===V[1]&&e[2]===V[2]&&(e[3]||("http:"===e[1]?80:443))==(V[3]||("http:"===V[1]?80:443))));
m.data&&m.processData&&"string"!==typeof m.data&&(m.data=c.param(m.data,m.traditional));sb(Sb,m,b,t);if(2===J)return t;(l=m.global)&&0===c.active++&&c.event.trigger("ajaxStart");m.type=m.type.toUpperCase();m.hasContent=!Pc.test(m.type);g=m.url;m.hasContent||(m.data&&(g=m.url+=(Xa.test(g)?"&":"?")+m.data,delete m.data),!1===m.cache&&(m.url=Pb.test(g)?g.replace(Pb,"$1_="+Wa++):g+(Xa.test(g)?"&":"?")+"_="+Wa++));m.ifModified&&(c.lastModified[g]&&t.setRequestHeader("If-Modified-Since",c.lastModified[g]),
c.etag[g]&&t.setRequestHeader("If-None-Match",c.etag[g]));(m.data&&m.hasContent&&!1!==m.contentType||b.contentType)&&t.setRequestHeader("Content-Type",m.contentType);t.setRequestHeader("Accept",m.dataTypes[0]&&m.accepts[m.dataTypes[0]]?m.accepts[m.dataTypes[0]]+("*"!==m.dataTypes[0]?", "+Tb+"; q=0.01":""):m.accepts["*"]);for(f in m.headers)t.setRequestHeader(f,m.headers[f]);if(m.beforeSend&&(!1===m.beforeSend.call(r,t,m)||2===J))return t.abort();G="abort";for(f in{success:1,error:1,complete:1})t[f](m[f]);
if(n=sb(Ja,m,b,t)){t.readyState=1;l&&z.trigger("ajaxSend",[t,m]);m.async&&0<m.timeout&&(k=setTimeout(function(){t.abort("timeout")},m.timeout));try{J=1,n.send(B,d)}catch(L){if(2>J)d(-1,L);else throw L;}}else d(-1,"No Transport");return t},getScript:function(a,b){return c.get(a,p,b,"script")},getJSON:function(a,b,d){return c.get(a,b,d,"json")}});c.ajaxSetup({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},contents:{script:/(?:java|ecma)script/},
converters:{"text script":function(a){c.globalEval(a);return a}}});c.ajaxPrefilter("script",function(a){a.cache===p&&(a.cache=!1);a.crossDomain&&(a.type="GET",a.global=!1)});c.ajaxTransport("script",function(a){if(a.crossDomain){var b,d=q.head||c("head")[0]||q.documentElement;return{send:function(c,f){b=q.createElement("script");b.async=!0;a.scriptCharset&&(b.charset=a.scriptCharset);b.src=a.url;b.onload=b.onreadystatechange=function(a,c){if(c||!b.readyState||/loaded|complete/.test(b.readyState))b.onload=
b.onreadystatechange=null,b.parentNode&&b.parentNode.removeChild(b),b=null,c||f(200,"success")};d.insertBefore(b,d.firstChild)},abort:function(){if(b)b.onload(p,!0)}}}});var Ub=[],Ya=/(=)\?(?=&|$)|\?\?/;c.ajaxSetup({jsonp:"callback",jsonpCallback:function(){var a=Ub.pop()||c.expando+"_"+Wa++;this[a]=!0;return a}});c.ajaxPrefilter("json jsonp",function(a,b,d){var e,f,g,h=!1!==a.jsonp&&(Ya.test(a.url)?"url":"string"===typeof a.data&&!(a.contentType||"").indexOf("application/x-www-form-urlencoded")&&
Ya.test(a.data)&&"data");if(h||"jsonp"===a.dataTypes[0])return e=a.jsonpCallback=c.isFunction(a.jsonpCallback)?a.jsonpCallback():a.jsonpCallback,h?a[h]=a[h].replace(Ya,"$1"+e):!1!==a.jsonp&&(a.url+=(Xa.test(a.url)?"&":"?")+a.jsonp+"="+e),a.converters["script json"]=function(){g||c.error(e+" was not called");return g[0]},a.dataTypes[0]="json",f=n[e],n[e]=function(){g=arguments},d.always(function(){n[e]=f;a[e]&&(a.jsonpCallback=b.jsonpCallback,Ub.push(e));g&&c.isFunction(f)&&f(g[0]);g=f=p}),"script"});
var ka,oa,Rc=0,Za=n.ActiveXObject&&function(){for(var a in ka)ka[a](p,!0)};c.ajaxSettings.xhr=n.ActiveXObject?function(){var a;if(!(a=!this.isLocal&&tb()))a:{try{a=new n.ActiveXObject("Microsoft.XMLHTTP");break a}catch(b){}a=void 0}return a}:tb;oa=c.ajaxSettings.xhr();c.support.cors=!!oa&&"withCredentials"in oa;(oa=c.support.ajax=!!oa)&&c.ajaxTransport(function(a){if(!a.crossDomain||c.support.cors){var b;return{send:function(d,e){var f,g,h=a.xhr();a.username?h.open(a.type,a.url,a.async,a.username,
a.password):h.open(a.type,a.url,a.async);if(a.xhrFields)for(g in a.xhrFields)h[g]=a.xhrFields[g];a.mimeType&&h.overrideMimeType&&h.overrideMimeType(a.mimeType);a.crossDomain||d["X-Requested-With"]||(d["X-Requested-With"]="XMLHttpRequest");try{for(g in d)h.setRequestHeader(g,d[g])}catch(k){}h.send(a.hasContent&&a.data||null);b=function(d,g){var k,l,m,n;try{if(b&&(g||4===h.readyState))if(b=p,f&&(h.onreadystatechange=c.noop,Za&&delete ka[f]),g)4!==h.readyState&&h.abort();else{n={};k=h.status;l=h.getAllResponseHeaders();
"string"===typeof h.responseText&&(n.text=h.responseText);try{m=h.statusText}catch(Ca){m=""}k||!a.isLocal||a.crossDomain?1223===k&&(k=204):k=n.text?200:404}}catch(Ca){g||e(-1,Ca)}n&&e(k,m,n,l)};a.async?4===h.readyState?setTimeout(b):(f=++Rc,Za&&(ka||(ka={},c(n).unload(Za)),ka[f]=b),h.onreadystatechange=b):b()},abort:function(){b&&b(p,!0)}}}});var T,Ea,Sc=/^(?:toggle|show|hide)$/,Tc=new RegExp("^(?:([+-])=|)("+Ba+")([a-z%]*)$","i"),Uc=/queueHooks$/,ra=[function(a,b,d){var e,f,g,h,k,l,n=this,p=a.style,
m={},q=[],w=a.nodeType&&ma(a);d.queue||(k=c._queueHooks(a,"fx"),null==k.unqueued&&(k.unqueued=0,l=k.empty.fire,k.empty.fire=function(){k.unqueued||l()}),k.unqueued++,n.always(function(){n.always(function(){k.unqueued--;c.queue(a,"fx").length||k.empty.fire()})}));1===a.nodeType&&("height"in b||"width"in b)&&(d.overflow=[p.overflow,p.overflowX,p.overflowY],"inline"===c.css(a,"display")&&"none"===c.css(a,"float")&&(c.support.inlineBlockNeedsLayout&&"inline"!==lb(a.nodeName)?p.zoom=1:p.display="inline-block"));
d.overflow&&(p.overflow="hidden",c.support.shrinkWrapBlocks||n.always(function(){p.overflow=d.overflow[0];p.overflowX=d.overflow[1];p.overflowY=d.overflow[2]}));for(f in b)g=b[f],Sc.exec(g)&&(delete b[f],e=e||"toggle"===g,g!==(w?"hide":"show")&&q.push(f));if(b=q.length)for(g=c._data(a,"fxshow")||c._data(a,"fxshow",{}),("hidden"in g)&&(w=g.hidden),e&&(g.hidden=!w),w?c(a).show():n.done(function(){c(a).hide()}),n.done(function(){var b;c._removeData(a,"fxshow");for(b in m)c.style(a,b,m[b])}),f=0;f<b;f++)e=
q[f],h=n.createTween(e,w?g[e]:0),m[e]=g[e]||c.style(a,e),e in g||(g[e]=h.start,w&&(h.end=h.start,h.start="width"===e||"height"===e?1:0))}],da={"*":[function(a,b){var d,e,f=this.createTween(a,b),g=Tc.exec(b),h=f.cur(),k=+h||0,l=1,n=20;if(g){d=+g[2];e=g[3]||(c.cssNumber[a]?"":"px");if("px"!==e&&k){k=c.css(f.elem,a,!0)||d||1;do l=l||".5",k/=l,c.style(f.elem,a,k+e);while(l!==(l=f.cur()/h)&&1!==l&&--n)}f.unit=e;f.start=k;f.end=g[1]?k+(g[1]+1)*d:d}return f}]};c.Animation=c.extend(vb,{tweener:function(a,
b){c.isFunction(a)?(b=a,a=["*"]):a=a.split(" ");for(var d,e=0,f=a.length;e<f;e++)d=a[e],da[d]=da[d]||[],da[d].unshift(b)},prefilter:function(a,b){b?ra.unshift(a):ra.push(a)}});c.Tween=H;H.prototype={constructor:H,init:function(a,b,d,e,f,g){this.elem=a;this.prop=d;this.easing=f||"swing";this.options=b;this.start=this.now=this.cur();this.end=e;this.unit=g||(c.cssNumber[d]?"":"px")},cur:function(){var a=H.propHooks[this.prop];return a&&a.get?a.get(this):H.propHooks._default.get(this)},run:function(a){var b,
d=H.propHooks[this.prop];this.pos=this.options.duration?b=c.easing[this.easing](a,this.options.duration*a,0,1,this.options.duration):b=a;this.now=(this.end-this.start)*b+this.start;this.options.step&&this.options.step.call(this.elem,this.now,this);d&&d.set?d.set(this):H.propHooks._default.set(this);return this}};H.prototype.init.prototype=H.prototype;H.propHooks={_default:{get:function(a){return null==a.elem[a.prop]||a.elem.style&&null!=a.elem.style[a.prop]?(a=c.css(a.elem,a.prop,""))&&"auto"!==a?
a:0:a.elem[a.prop]},set:function(a){if(c.fx.step[a.prop])c.fx.step[a.prop](a);else a.elem.style&&(null!=a.elem.style[c.cssProps[a.prop]]||c.cssHooks[a.prop])?c.style(a.elem,a.prop,a.now+a.unit):a.elem[a.prop]=a.now}}};H.propHooks.scrollTop=H.propHooks.scrollLeft={set:function(a){a.elem.nodeType&&a.elem.parentNode&&(a.elem[a.prop]=a.now)}};c.each(["toggle","show","hide"],function(a,b){var d=c.fn[b];c.fn[b]=function(a,c,g){return null==a||"boolean"===typeof a?d.apply(this,arguments):this.animate(sa(b,
!0),a,c,g)}});c.fn.extend({fadeTo:function(a,b,c,e){return this.filter(ma).css("opacity",0).show().end().animate({opacity:b},a,c,e)},animate:function(a,b,d,e){var f=c.isEmptyObject(a),g=c.speed(b,d,e),h=function(){var b=vb(this,c.extend({},a),g);h.finish=function(){b.stop(!0)};(f||c._data(this,"finish"))&&b.stop(!0)};h.finish=h;return f||!1===g.queue?this.each(h):this.queue(g.queue,h)},stop:function(a,b,d){var e=function(a){var b=a.stop;delete a.stop;b(d)};"string"!==typeof a&&(d=b,b=a,a=p);b&&!1!==
a&&this.queue(a||"fx",[]);return this.each(function(){var b=!0,g=null!=a&&a+"queueHooks",h=c.timers,k=c._data(this);if(g)k[g]&&k[g].stop&&e(k[g]);else for(g in k)k[g]&&k[g].stop&&Uc.test(g)&&e(k[g]);for(g=h.length;g--;)h[g].elem!==this||null!=a&&h[g].queue!==a||(h[g].anim.stop(d),b=!1,h.splice(g,1));!b&&d||c.dequeue(this,a)})},finish:function(a){!1!==a&&(a=a||"fx");return this.each(function(){var b,d=c._data(this),e=d[a+"queue"];b=d[a+"queueHooks"];var f=c.timers,g=e?e.length:0;d.finish=!0;c.queue(this,
a,[]);b&&b.cur&&b.cur.finish&&b.cur.finish.call(this);for(b=f.length;b--;)f[b].elem===this&&f[b].queue===a&&(f[b].anim.stop(!0),f.splice(b,1));for(b=0;b<g;b++)e[b]&&e[b].finish&&e[b].finish.call(this);delete d.finish})}});c.each({slideDown:sa("show"),slideUp:sa("hide"),slideToggle:sa("toggle"),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},function(a,b){c.fn[a]=function(a,c,f){return this.animate(b,a,c,f)}});c.speed=function(a,b,d){var e=a&&"object"===typeof a?c.extend({},
a):{complete:d||!d&&b||c.isFunction(a)&&a,duration:a,easing:d&&b||b&&!c.isFunction(b)&&b};e.duration=c.fx.off?0:"number"===typeof e.duration?e.duration:e.duration in c.fx.speeds?c.fx.speeds[e.duration]:c.fx.speeds._default;if(null==e.queue||!0===e.queue)e.queue="fx";e.old=e.complete;e.complete=function(){c.isFunction(e.old)&&e.old.call(this);e.queue&&c.dequeue(this,e.queue)};return e};c.easing={linear:function(a){return a},swing:function(a){return.5-Math.cos(a*Math.PI)/2}};c.timers=[];c.fx=H.prototype.init;
c.fx.tick=function(){var a,b=c.timers,d=0;for(T=c.now();d<b.length;d++)a=b[d],a()||b[d]!==a||b.splice(d--,1);b.length||c.fx.stop();T=p};c.fx.timer=function(a){a()&&c.timers.push(a)&&c.fx.start()};c.fx.interval=13;c.fx.start=function(){Ea||(Ea=setInterval(c.fx.tick,c.fx.interval))};c.fx.stop=function(){clearInterval(Ea);Ea=null};c.fx.speeds={slow:600,fast:200,_default:400};c.fx.step={};c.expr&&c.expr.filters&&(c.expr.filters.animated=function(a){return c.grep(c.timers,function(b){return a===b.elem}).length});
c.fn.offset=function(a){if(arguments.length)return a===p?this:this.each(function(b){c.offset.setOffset(this,a,b)});var b,d,e={top:0,left:0},f=(d=this[0])&&d.ownerDocument;if(f){b=f.documentElement;if(!c.contains(b,d))return e;typeof d.getBoundingClientRect!==O&&(e=d.getBoundingClientRect());d=wb(f);return{top:e.top+(d.pageYOffset||b.scrollTop)-(b.clientTop||0),left:e.left+(d.pageXOffset||b.scrollLeft)-(b.clientLeft||0)}}};c.offset={setOffset:function(a,b,d){var e=c.css(a,"position");"static"===e&&
(a.style.position="relative");var f=c(a),g=f.offset(),h=c.css(a,"top"),k=c.css(a,"left"),l={};("absolute"===e||"fixed"===e)&&-1<c.inArray("auto",[h,k])?(k=f.position(),e=k.top,k=k.left):(e=parseFloat(h)||0,k=parseFloat(k)||0);c.isFunction(b)&&(b=b.call(a,d,g));null!=b.top&&(l.top=b.top-g.top+e);null!=b.left&&(l.left=b.left-g.left+k);"using"in b?b.using.call(a,l):f.css(l)}};c.fn.extend({position:function(){if(this[0]){var a,b,d={top:0,left:0},e=this[0];"fixed"===c.css(e,"position")?b=e.getBoundingClientRect():
(a=this.offsetParent(),b=this.offset(),c.nodeName(a[0],"html")||(d=a.offset()),d.top+=c.css(a[0],"borderTopWidth",!0),d.left+=c.css(a[0],"borderLeftWidth",!0));return{top:b.top-d.top-c.css(e,"marginTop",!0),left:b.left-d.left-c.css(e,"marginLeft",!0)}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||q.documentElement;a&&!c.nodeName(a,"html")&&"static"===c.css(a,"position");)a=a.offsetParent;return a||q.documentElement})}});c.each({scrollLeft:"pageXOffset",scrollTop:"pageYOffset"},
function(a,b){var d=/Y/.test(b);c.fn[a]=function(e){return c.access(this,function(a,e,h){var f=wb(a);if(h===p)return f?b in f?f[b]:f.document.documentElement[e]:a[e];f?f.scrollTo(d?c(f).scrollLeft():h,d?h:c(f).scrollTop()):a[e]=h},a,e,arguments.length,null)}});c.each({Height:"height",Width:"width"},function(a,b){c.each({padding:"inner"+a,content:b,"":"outer"+a},function(d,e){c.fn[e]=function(e,g){var f=arguments.length&&(d||"boolean"!==typeof e),k=d||(!0===e||!0===g?"margin":"border");return c.access(this,
function(b,d,e){return c.isWindow(b)?b.document.documentElement["client"+a]:9===b.nodeType?(d=b.documentElement,Math.max(b.body["scroll"+a],d["scroll"+a],b.body["offset"+a],d["offset"+a],d["client"+a])):e===p?c.css(b,d,k):c.style(b,d,e,k)},b,f?e:p,f,null)}})});n.jQuery=n.$=c;"function"===typeof define&&define.amd&&define.amd.jQuery&&define("jquery",[],function(){return c})})(window);
